// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_myPos_MainPage()
{
    return winrt::detach_abi(winrt::make<winrt::myPos::factory_implementation::MainPage>());
}
WINRT_EXPORT namespace winrt::myPos
{
    MainPage::MainPage() :
        MainPage(make<myPos::implementation::MainPage>())
    {
    }
}
