// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_BVLinearGradient_1_H
#define WINRT_BVLinearGradient_1_H
#include "winrt/impl/BVLinearGradient.0.h"
WINRT_EXPORT namespace winrt::BVLinearGradient
{
    struct WINRT_IMPL_EMPTY_BASES IBVLinearGradientModule :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBVLinearGradientModule>
    {
        IBVLinearGradientModule(std::nullptr_t = nullptr) noexcept {}
        IBVLinearGradientModule(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IBVLinearGradientModuleFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBVLinearGradientModuleFactory>
    {
        IBVLinearGradientModuleFactory(std::nullptr_t = nullptr) noexcept {}
        IBVLinearGradientModuleFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IReactPackageProvider :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IReactPackageProvider>
    {
        IReactPackageProvider(std::nullptr_t = nullptr) noexcept {}
        IReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
