// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_BVLinearGradient_2_H
#define WINRT_BVLinearGradient_2_H
#include "winrt/impl/Microsoft.ReactNative.1.h"
#include "winrt/impl/Windows.UI.Composition.1.h"
#include "winrt/impl/Windows.UI.Xaml.1.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.1.h"
#include "winrt/impl/BVLinearGradient.1.h"
WINRT_EXPORT namespace winrt::BVLinearGradient
{
    struct WINRT_IMPL_EMPTY_BASES BVLinearGradientModule : winrt::BVLinearGradient::IBVLinearGradientModule,
        impl::base<BVLinearGradientModule, winrt::Windows::UI::Xaml::Controls::Panel, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<BVLinearGradientModule, winrt::Windows::UI::Xaml::Controls::IPanel, winrt::Windows::UI::Xaml::Controls::IPanel2, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        BVLinearGradientModule(std::nullptr_t) noexcept {}
        BVLinearGradientModule(void* ptr, take_ownership_from_abi_t) noexcept : winrt::BVLinearGradient::IBVLinearGradientModule(ptr, take_ownership_from_abi) {}
        explicit BVLinearGradientModule(winrt::Microsoft::ReactNative::IReactContext const& context);
    };
    struct WINRT_IMPL_EMPTY_BASES ReactPackageProvider : winrt::BVLinearGradient::IReactPackageProvider,
        impl::require<ReactPackageProvider, winrt::Microsoft::ReactNative::IReactPackageProvider>
    {
        ReactPackageProvider(std::nullptr_t) noexcept {}
        ReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::BVLinearGradient::IReactPackageProvider(ptr, take_ownership_from_abi) {}
        ReactPackageProvider();
    };
}
#endif
