// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_BVLinearGradient_0_H
#define WINRT_BVLinearGradient_0_H
WINRT_EXPORT namespace winrt::Microsoft::ReactNative
{
    struct IJSValueReader;
    struct IReactContext;
}
WINRT_EXPORT namespace winrt::BVLinearGradient
{
    struct IBVLinearGradientModule;
    struct IBVLinearGradientModuleFactory;
    struct IReactPackageProvider;
    struct BVLinearGradientModule;
    struct ReactPackageProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::BVLinearGradient::IBVLinearGradientModule>{ using type = interface_category; };
    template <> struct category<winrt::BVLinearGradient::IBVLinearGradientModuleFactory>{ using type = interface_category; };
    template <> struct category<winrt::BVLinearGradient::IReactPackageProvider>{ using type = interface_category; };
    template <> struct category<winrt::BVLinearGradient::BVLinearGradientModule>{ using type = class_category; };
    template <> struct category<winrt::BVLinearGradient::ReactPackageProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::BVLinearGradient::BVLinearGradientModule> = L"BVLinearGradient.BVLinearGradientModule";
    template <> inline constexpr auto& name_v<winrt::BVLinearGradient::ReactPackageProvider> = L"BVLinearGradient.ReactPackageProvider";
    template <> inline constexpr auto& name_v<winrt::BVLinearGradient::IBVLinearGradientModule> = L"BVLinearGradient.IBVLinearGradientModule";
    template <> inline constexpr auto& name_v<winrt::BVLinearGradient::IBVLinearGradientModuleFactory> = L"BVLinearGradient.IBVLinearGradientModuleFactory";
    template <> inline constexpr auto& name_v<winrt::BVLinearGradient::IReactPackageProvider> = L"BVLinearGradient.IReactPackageProvider";
    template <> inline constexpr guid guid_v<winrt::BVLinearGradient::IBVLinearGradientModule>{ 0x5034F95A,0x6097,0x5BF0,{ 0x94,0x94,0x39,0x3D,0xA7,0x13,0x53,0x06 } }; // 5034F95A-6097-5BF0-9494-393DA7135306
    template <> inline constexpr guid guid_v<winrt::BVLinearGradient::IBVLinearGradientModuleFactory>{ 0x9DB029BA,0xDB29,0x54B4,{ 0x8C,0x16,0x52,0x7C,0x49,0x0D,0x13,0x0A } }; // 9DB029BA-DB29-54B4-8C16-527C490D130A
    template <> inline constexpr guid guid_v<winrt::BVLinearGradient::IReactPackageProvider>{ 0x715A6DE5,0xEEEA,0x5EF5,{ 0x88,0x67,0xCA,0x84,0xFB,0x71,0x20,0x3D } }; // 715A6DE5-EEEA-5EF5-8867-CA84FB71203D
    template <> struct default_interface<winrt::BVLinearGradient::BVLinearGradientModule>{ using type = winrt::BVLinearGradient::IBVLinearGradientModule; };
    template <> struct default_interface<winrt::BVLinearGradient::ReactPackageProvider>{ using type = winrt::BVLinearGradient::IReactPackageProvider; };
    template <> struct abi<winrt::BVLinearGradient::IBVLinearGradientModule>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall UpdateProperties(void*) noexcept = 0;
            virtual int32_t __stdcall DispatchCommand(void*, void*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::BVLinearGradient::IBVLinearGradientModuleFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::BVLinearGradient::IReactPackageProvider>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_BVLinearGradient_IBVLinearGradientModule
    {
        auto UpdateProperties(winrt::Microsoft::ReactNative::IJSValueReader const& reader) const;
        auto DispatchCommand(param::hstring const& commandId, winrt::Microsoft::ReactNative::IJSValueReader const& commandArgsReader) const;
    };
    template <> struct consume<winrt::BVLinearGradient::IBVLinearGradientModule>
    {
        template <typename D> using type = consume_BVLinearGradient_IBVLinearGradientModule<D>;
    };
    template <typename D>
    struct consume_BVLinearGradient_IBVLinearGradientModuleFactory
    {
        auto CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context) const;
    };
    template <> struct consume<winrt::BVLinearGradient::IBVLinearGradientModuleFactory>
    {
        template <typename D> using type = consume_BVLinearGradient_IBVLinearGradientModuleFactory<D>;
    };
    template <typename D>
    struct consume_BVLinearGradient_IReactPackageProvider
    {
    };
    template <> struct consume<winrt::BVLinearGradient::IReactPackageProvider>
    {
        template <typename D> using type = consume_BVLinearGradient_IReactPackageProvider<D>;
    };
}
#endif
