// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_myPos_1_H
#define WINRT_myPos_1_H
#include "winrt/impl/myPos.0.h"
WINRT_EXPORT namespace winrt::myPos
{
    struct WINRT_IMPL_EMPTY_BASES IMainPage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainPage>
    {
        IMainPage(std::nullptr_t = nullptr) noexcept {}
        IMainPage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
