// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_myPos_0_H
#define WINRT_myPos_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::myPos
{
    struct IMainPage;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::myPos::IMainPage>{ using type = interface_category; };
    template <> struct category<winrt::myPos::MainPage>{ using type = class_category; };
    template <> struct category<winrt::myPos::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::myPos::MainPage> = L"myPos.MainPage";
    template <> inline constexpr auto& name_v<winrt::myPos::XamlMetaDataProvider> = L"myPos.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::myPos::IMainPage> = L"myPos.IMainPage";
    template <> inline constexpr guid guid_v<winrt::myPos::IMainPage>{ 0x648C9513,0xFF66,0x5673,{ 0x81,0xED,0xE1,0x69,0xD8,0xB5,0x5E,0xDC } }; // 648C9513-FF66-5673-81ED-E169D8B55EDC
    template <> struct default_interface<winrt::myPos::MainPage>{ using type = winrt::myPos::IMainPage; };
    template <> struct default_interface<winrt::myPos::XamlMetaDataProvider>{ using type = winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::myPos::IMainPage>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_myPos_IMainPage
    {
    };
    template <> struct consume<winrt::myPos::IMainPage>
    {
        template <typename D> using type = consume_myPos_IMainPage<D>;
    };
}
#endif
