// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_ReactNativeAsyncStorage_2_H
#define WINRT_ReactNativeAsyncStorage_2_H
#include "winrt/impl/Microsoft.ReactNative.1.h"
#include "winrt/impl/ReactNativeAsyncStorage.1.h"
WINRT_EXPORT namespace winrt::ReactNativeAsyncStorage
{
    struct WINRT_IMPL_EMPTY_BASES ReactPackageProvider : winrt::ReactNativeAsyncStorage::IReactPackageProvider,
        impl::require<ReactPackageProvider, winrt::Microsoft::ReactNative::IReactPackageProvider>
    {
        ReactPackageProvider(std::nullptr_t) noexcept {}
        ReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::ReactNativeAsyncStorage::IReactPackageProvider(ptr, take_ownership_from_abi) {}
        ReactPackageProvider();
    };
}
#endif
