// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_ReactNativeAsyncStorage_0_H
#define WINRT_ReactNativeAsyncStorage_0_H
WINRT_EXPORT namespace winrt::ReactNativeAsyncStorage
{
    struct IReactPackageProvider;
    struct ReactPackageProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::ReactNativeAsyncStorage::IReactPackageProvider>{ using type = interface_category; };
    template <> struct category<winrt::ReactNativeAsyncStorage::ReactPackageProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::ReactNativeAsyncStorage::ReactPackageProvider> = L"ReactNativeAsyncStorage.ReactPackageProvider";
    template <> inline constexpr auto& name_v<winrt::ReactNativeAsyncStorage::IReactPackageProvider> = L"ReactNativeAsyncStorage.IReactPackageProvider";
    template <> inline constexpr guid guid_v<winrt::ReactNativeAsyncStorage::IReactPackageProvider>{ 0xE45CA6F3,0x04AA,0x50BE,{ 0xB2,0x77,0xD5,0xDC,0x05,0x66,0x5E,0x66 } }; // E45CA6F3-04AA-50BE-B277-D5DC05665E66
    template <> struct default_interface<winrt::ReactNativeAsyncStorage::ReactPackageProvider>{ using type = winrt::ReactNativeAsyncStorage::IReactPackageProvider; };
    template <> struct abi<winrt::ReactNativeAsyncStorage::IReactPackageProvider>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_ReactNativeAsyncStorage_IReactPackageProvider
    {
    };
    template <> struct consume<winrt::ReactNativeAsyncStorage::IReactPackageProvider>
    {
        template <typename D> using type = consume_ReactNativeAsyncStorage_IReactPackageProvider<D>;
    };
}
#endif
