// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_ReactNativeAsyncStorage_1_H
#define WINRT_ReactNativeAsyncStorage_1_H
#include "winrt/impl/ReactNativeAsyncStorage.0.h"
WINRT_EXPORT namespace winrt::ReactNativeAsyncStorage
{
    struct WINRT_IMPL_EMPTY_BASES IReactPackageProvider :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IReactPackageProvider>
    {
        IReactPackageProvider(std::nullptr_t = nullptr) noexcept {}
        IReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
