// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_ReactNativeShare_0_H
#define WINRT_ReactNativeShare_0_H
WINRT_EXPORT namespace winrt::ReactNativeShare
{
    struct IReactPackageProvider;
    struct ReactPackageProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::ReactNativeShare::IReactPackageProvider>{ using type = interface_category; };
    template <> struct category<winrt::ReactNativeShare::ReactPackageProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::ReactNativeShare::ReactPackageProvider> = L"ReactNativeShare.ReactPackageProvider";
    template <> inline constexpr auto& name_v<winrt::ReactNativeShare::IReactPackageProvider> = L"ReactNativeShare.IReactPackageProvider";
    template <> inline constexpr guid guid_v<winrt::ReactNativeShare::IReactPackageProvider>{ 0x70C0F1C3,0x842A,0x53EE,{ 0xA3,0x0F,0x0B,0x79,0x49,0x21,0x62,0xD4 } }; // 70C0F1C3-842A-53EE-A30F-0B79492162D4
    template <> struct default_interface<winrt::ReactNativeShare::ReactPackageProvider>{ using type = winrt::ReactNativeShare::IReactPackageProvider; };
    template <> struct abi<winrt::ReactNativeShare::IReactPackageProvider>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_ReactNativeShare_IReactPackageProvider
    {
    };
    template <> struct consume<winrt::ReactNativeShare::IReactPackageProvider>
    {
        template <typename D> using type = consume_ReactNativeShare_IReactPackageProvider<D>;
    };
}
#endif
