// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_RNScreens_0_H
#define WINRT_RNScreens_0_H
WINRT_EXPORT namespace winrt::Microsoft::ReactNative
{
    struct IJSValueReader;
    struct IReactContext;
}
WINRT_EXPORT namespace winrt::RNScreens
{
    struct IRNScreensModule;
    struct IRNScreensModuleFactory;
    struct IReactPackageProvider;
    struct RNScreensModule;
    struct ReactPackageProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::RNScreens::IRNScreensModule>{ using type = interface_category; };
    template <> struct category<winrt::RNScreens::IRNScreensModuleFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNScreens::IReactPackageProvider>{ using type = interface_category; };
    template <> struct category<winrt::RNScreens::RNScreensModule>{ using type = class_category; };
    template <> struct category<winrt::RNScreens::ReactPackageProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::RNScreens::RNScreensModule> = L"RNScreens.RNScreensModule";
    template <> inline constexpr auto& name_v<winrt::RNScreens::ReactPackageProvider> = L"RNScreens.ReactPackageProvider";
    template <> inline constexpr auto& name_v<winrt::RNScreens::IRNScreensModule> = L"RNScreens.IRNScreensModule";
    template <> inline constexpr auto& name_v<winrt::RNScreens::IRNScreensModuleFactory> = L"RNScreens.IRNScreensModuleFactory";
    template <> inline constexpr auto& name_v<winrt::RNScreens::IReactPackageProvider> = L"RNScreens.IReactPackageProvider";
    template <> inline constexpr guid guid_v<winrt::RNScreens::IRNScreensModule>{ 0xEFA7EFD9,0xD776,0x5ED1,{ 0xB1,0xEC,0x15,0x4B,0x24,0xFE,0x0C,0xD1 } }; // EFA7EFD9-D776-5ED1-B1EC-154B24FE0CD1
    template <> inline constexpr guid guid_v<winrt::RNScreens::IRNScreensModuleFactory>{ 0xEF000D01,0x7C5D,0x5B13,{ 0xB6,0x99,0x3F,0xBE,0xCF,0xDA,0xDA,0xB8 } }; // EF000D01-7C5D-5B13-B699-3FBECFDADAB8
    template <> inline constexpr guid guid_v<winrt::RNScreens::IReactPackageProvider>{ 0x8C182946,0x9A8F,0x5D04,{ 0xB6,0xAC,0xDB,0xEE,0x4E,0xF5,0x37,0x36 } }; // 8C182946-9A8F-5D04-B6AC-DBEE4EF53736
    template <> struct default_interface<winrt::RNScreens::RNScreensModule>{ using type = winrt::RNScreens::IRNScreensModule; };
    template <> struct default_interface<winrt::RNScreens::ReactPackageProvider>{ using type = winrt::RNScreens::IReactPackageProvider; };
    template <> struct abi<winrt::RNScreens::IRNScreensModule>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall UpdateProperties(void*) noexcept = 0;
            virtual int32_t __stdcall DispatchCommand(void*, void*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNScreens::IRNScreensModuleFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNScreens::IReactPackageProvider>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_RNScreens_IRNScreensModule
    {
        auto UpdateProperties(winrt::Microsoft::ReactNative::IJSValueReader const& reader) const;
        auto DispatchCommand(param::hstring const& commandId, winrt::Microsoft::ReactNative::IJSValueReader const& commandArgsReader) const;
    };
    template <> struct consume<winrt::RNScreens::IRNScreensModule>
    {
        template <typename D> using type = consume_RNScreens_IRNScreensModule<D>;
    };
    template <typename D>
    struct consume_RNScreens_IRNScreensModuleFactory
    {
        auto CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context) const;
    };
    template <> struct consume<winrt::RNScreens::IRNScreensModuleFactory>
    {
        template <typename D> using type = consume_RNScreens_IRNScreensModuleFactory<D>;
    };
    template <typename D>
    struct consume_RNScreens_IReactPackageProvider
    {
    };
    template <> struct consume<winrt::RNScreens::IReactPackageProvider>
    {
        template <typename D> using type = consume_RNScreens_IReactPackageProvider<D>;
    };
}
#endif
