// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_RNScreens_1_H
#define WINRT_RNScreens_1_H
#include "winrt/impl/RNScreens.0.h"
WINRT_EXPORT namespace winrt::RNScreens
{
    struct WINRT_IMPL_EMPTY_BASES IRNScreensModule :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRNScreensModule>
    {
        IRNScreensModule(std::nullptr_t = nullptr) noexcept {}
        IRNScreensModule(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRNScreensModuleFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRNScreensModuleFactory>
    {
        IRNScreensModuleFactory(std::nullptr_t = nullptr) noexcept {}
        IRNScreensModuleFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IReactPackageProvider :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IReactPackageProvider>
    {
        IReactPackageProvider(std::nullptr_t = nullptr) noexcept {}
        IReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
