// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_RNSVG_1_H
#define WINRT_RNSVG_1_H
#include "winrt/impl/RNSVG.0.h"
WINRT_EXPORT namespace winrt::RNSVG
{
    struct WINRT_IMPL_EMPTY_BASES IBrushView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBrushView>
    {
        IBrushView(std::nullptr_t = nullptr) noexcept {}
        IBrushView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IBrushView2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBrushView2>
    {
        IBrushView2(std::nullptr_t = nullptr) noexcept {}
        IBrushView2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IBrushViewFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBrushViewFactory>
    {
        IBrushViewFactory(std::nullptr_t = nullptr) noexcept {}
        IBrushViewFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICircleView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICircleView>
    {
        ICircleView(std::nullptr_t = nullptr) noexcept {}
        ICircleView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICircleViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICircleViewManager>
    {
        ICircleViewManager(std::nullptr_t = nullptr) noexcept {}
        ICircleViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IClipPathView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClipPathView>
    {
        IClipPathView(std::nullptr_t = nullptr) noexcept {}
        IClipPathView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IClipPathViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClipPathViewManager>
    {
        IClipPathViewManager(std::nullptr_t = nullptr) noexcept {}
        IClipPathViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ID2DBrush :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ID2DBrush>
    {
        ID2DBrush(std::nullptr_t = nullptr) noexcept {}
        ID2DBrush(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ID2DDevice :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ID2DDevice>
    {
        ID2DDevice(std::nullptr_t = nullptr) noexcept {}
        ID2DDevice(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ID2DDeviceContext :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ID2DDeviceContext>
    {
        ID2DDeviceContext(std::nullptr_t = nullptr) noexcept {}
        ID2DDeviceContext(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ID2DGeometry :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ID2DGeometry>
    {
        ID2DGeometry(std::nullptr_t = nullptr) noexcept {}
        ID2DGeometry(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IDefsView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDefsView>
    {
        IDefsView(std::nullptr_t = nullptr) noexcept {}
        IDefsView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IDefsViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IDefsViewManager>
    {
        IDefsViewManager(std::nullptr_t = nullptr) noexcept {}
        IDefsViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IEllipseView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IEllipseView>
    {
        IEllipseView(std::nullptr_t = nullptr) noexcept {}
        IEllipseView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IEllipseViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IEllipseViewManager>
    {
        IEllipseViewManager(std::nullptr_t = nullptr) noexcept {}
        IEllipseViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IGroupView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IGroupView>
    {
        IGroupView(std::nullptr_t = nullptr) noexcept {}
        IGroupView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IGroupView2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IGroupView2>
    {
        IGroupView2(std::nullptr_t = nullptr) noexcept {}
        IGroupView2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IGroupViewFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IGroupViewFactory>
    {
        IGroupViewFactory(std::nullptr_t = nullptr) noexcept {}
        IGroupViewFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IGroupViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IGroupViewManager>
    {
        IGroupViewManager(std::nullptr_t = nullptr) noexcept {}
        IGroupViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IGroupViewManagerFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IGroupViewManagerFactory>
    {
        IGroupViewManagerFactory(std::nullptr_t = nullptr) noexcept {}
        IGroupViewManagerFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IImageView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IImageView>
    {
        IImageView(std::nullptr_t = nullptr) noexcept {}
        IImageView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IImageViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IImageViewManager>
    {
        IImageViewManager(std::nullptr_t = nullptr) noexcept {}
        IImageViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ILineView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILineView>
    {
        ILineView(std::nullptr_t = nullptr) noexcept {}
        ILineView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ILineViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILineViewManager>
    {
        ILineViewManager(std::nullptr_t = nullptr) noexcept {}
        ILineViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ILinearGradientView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILinearGradientView>
    {
        ILinearGradientView(std::nullptr_t = nullptr) noexcept {}
        ILinearGradientView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ILinearGradientViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ILinearGradientViewManager>
    {
        ILinearGradientViewManager(std::nullptr_t = nullptr) noexcept {}
        ILinearGradientViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMarkerView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMarkerView>
    {
        IMarkerView(std::nullptr_t = nullptr) noexcept {}
        IMarkerView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMarkerViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMarkerViewManager>
    {
        IMarkerViewManager(std::nullptr_t = nullptr) noexcept {}
        IMarkerViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMaskView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMaskView>
    {
        IMaskView(std::nullptr_t = nullptr) noexcept {}
        IMaskView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMaskViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMaskViewManager>
    {
        IMaskViewManager(std::nullptr_t = nullptr) noexcept {}
        IMaskViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IPathView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPathView>
    {
        IPathView(std::nullptr_t = nullptr) noexcept {}
        IPathView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IPathViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPathViewManager>
    {
        IPathViewManager(std::nullptr_t = nullptr) noexcept {}
        IPathViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IPatternView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPatternView>
    {
        IPatternView(std::nullptr_t = nullptr) noexcept {}
        IPatternView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IPatternViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPatternViewManager>
    {
        IPatternViewManager(std::nullptr_t = nullptr) noexcept {}
        IPatternViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRadialGradientView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRadialGradientView>
    {
        IRadialGradientView(std::nullptr_t = nullptr) noexcept {}
        IRadialGradientView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRadialGradientViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRadialGradientViewManager>
    {
        IRadialGradientViewManager(std::nullptr_t = nullptr) noexcept {}
        IRadialGradientViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IReactPackageProvider :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IReactPackageProvider>
    {
        IReactPackageProvider(std::nullptr_t = nullptr) noexcept {}
        IReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRectView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRectView>
    {
        IRectView(std::nullptr_t = nullptr) noexcept {}
        IRectView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRectViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRectViewManager>
    {
        IRectViewManager(std::nullptr_t = nullptr) noexcept {}
        IRectViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRenderable :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRenderable>
    {
        IRenderable(std::nullptr_t = nullptr) noexcept {}
        IRenderable(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRenderablePaper :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRenderablePaper>
    {
        IRenderablePaper(std::nullptr_t = nullptr) noexcept {}
        IRenderablePaper(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRenderableView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRenderableView>
    {
        IRenderableView(std::nullptr_t = nullptr) noexcept {}
        IRenderableView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRenderableView2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRenderableView2>
    {
        IRenderableView2(std::nullptr_t = nullptr) noexcept {}
        IRenderableView2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRenderableViewFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRenderableViewFactory>
    {
        IRenderableViewFactory(std::nullptr_t = nullptr) noexcept {}
        IRenderableViewFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRenderableViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRenderableViewManager>
    {
        IRenderableViewManager(std::nullptr_t = nullptr) noexcept {}
        IRenderableViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRenderableViewManagerFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRenderableViewManagerFactory>
    {
        IRenderableViewManagerFactory(std::nullptr_t = nullptr) noexcept {}
        IRenderableViewManagerFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISvgView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISvgView>
    {
        ISvgView(std::nullptr_t = nullptr) noexcept {}
        ISvgView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISvgView2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISvgView2>
    {
        ISvgView2(std::nullptr_t = nullptr) noexcept {}
        ISvgView2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISvgViewFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISvgViewFactory>
    {
        ISvgViewFactory(std::nullptr_t = nullptr) noexcept {}
        ISvgViewFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISvgViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISvgViewManager>
    {
        ISvgViewManager(std::nullptr_t = nullptr) noexcept {}
        ISvgViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISymbolView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISymbolView>
    {
        ISymbolView(std::nullptr_t = nullptr) noexcept {}
        ISymbolView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISymbolView2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISymbolView2>
    {
        ISymbolView2(std::nullptr_t = nullptr) noexcept {}
        ISymbolView2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISymbolViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISymbolViewManager>
    {
        ISymbolViewManager(std::nullptr_t = nullptr) noexcept {}
        ISymbolViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ITSpanView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITSpanView>
    {
        ITSpanView(std::nullptr_t = nullptr) noexcept {}
        ITSpanView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ITSpanView2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITSpanView2>
    {
        ITSpanView2(std::nullptr_t = nullptr) noexcept {}
        ITSpanView2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ITSpanViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITSpanViewManager>
    {
        ITSpanViewManager(std::nullptr_t = nullptr) noexcept {}
        ITSpanViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ITextView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextView>
    {
        ITextView(std::nullptr_t = nullptr) noexcept {}
        ITextView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ITextView2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextView2>
    {
        ITextView2(std::nullptr_t = nullptr) noexcept {}
        ITextView2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ITextViewFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextViewFactory>
    {
        ITextViewFactory(std::nullptr_t = nullptr) noexcept {}
        ITextViewFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ITextViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextViewManager>
    {
        ITextViewManager(std::nullptr_t = nullptr) noexcept {}
        ITextViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ITextViewManagerFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITextViewManagerFactory>
    {
        ITextViewManagerFactory(std::nullptr_t = nullptr) noexcept {}
        ITextViewManagerFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IUnsupportedSvgViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUnsupportedSvgViewManager>
    {
        IUnsupportedSvgViewManager(std::nullptr_t = nullptr) noexcept {}
        IUnsupportedSvgViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IUnsupportedSvgViewManagerFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUnsupportedSvgViewManagerFactory>
    {
        IUnsupportedSvgViewManagerFactory(std::nullptr_t = nullptr) noexcept {}
        IUnsupportedSvgViewManagerFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IUseView :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUseView>
    {
        IUseView(std::nullptr_t = nullptr) noexcept {}
        IUseView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IUseViewManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUseViewManager>
    {
        IUseViewManager(std::nullptr_t = nullptr) noexcept {}
        IUseViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
