// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_RNSVG_0_H
#define WINRT_RNSVG_0_H
WINRT_EXPORT namespace winrt::Microsoft::ReactNative
{
    struct IJSValueReader;
    struct IReactContext;
}
WINRT_EXPORT namespace winrt::Windows::Foundation
{
    struct Point;
    struct Rect;
    struct Size;
}
WINRT_EXPORT namespace winrt::Windows::Foundation::Numerics
{
}
WINRT_EXPORT namespace winrt::Windows::UI
{
    struct Color;
}
WINRT_EXPORT namespace winrt::Windows::UI::Xaml
{
    struct FrameworkElement;
}
WINRT_EXPORT namespace winrt::RNSVG
{
    enum class BaseProp : int32_t
    {
        Matrix = 0,
        Fill = 1,
        FillOpacity = 2,
        FillRule = 3,
        Stroke = 4,
        StrokeOpacity = 5,
        StrokeWidth = 6,
        StrokeMiterLimit = 7,
        StrokeDashOffset = 8,
        StrokeDashArray = 9,
        StrokeLineCap = 10,
        StrokeLineJoin = 11,
        Unknown = 12,
    };
    enum class FillRule : int32_t
    {
        EvenOdd = 0,
        NonZero = 1,
    };
    enum class FontProp : int32_t
    {
        FontSize = 0,
        FontWeight = 1,
        FontFamily = 2,
        Unknown = 3,
    };
    enum class LengthType : int32_t
    {
        Unknown = 0,
        Number = 1,
        Percentage = 2,
        EMS = 3,
        EXS = 4,
        Pixel = 5,
        Centimeter = 6,
        Millimeter = 7,
        Inch = 8,
        Point = 9,
        Pica = 10,
    };
    enum class LineCap : int32_t
    {
        Butt = 0,
        Round = 1,
        Square = 2,
    };
    enum class LineJoin : int32_t
    {
        Miter = 0,
        Round = 1,
        Bevel = 2,
    };
    enum class MeetOrSlice : int32_t
    {
        Meet = 0,
        Slice = 1,
        None = 2,
    };
    enum class SVGClass : int32_t
    {
        RNSVGGroup = 0,
        RNSVGPath = 1,
        RNSVGText = 2,
        RNSVGTSpan = 3,
        RNSVGTextPath = 4,
        RNSVGImage = 5,
        RNSVGCircle = 6,
        RNSVGEllipse = 7,
        RNSVGLine = 8,
        RNSVGRect = 9,
        RNSVGClipPath = 10,
        RNSVGDefs = 11,
        RNSVGUse = 12,
        RNSVGSymbol = 13,
        RNSVGLinearGradient = 14,
        RNSVGRadialGradient = 15,
        RNSVGPattern = 16,
        RNSVGMask = 17,
        RNSVGMarker = 18,
        RNSVGForeignObject = 19,
        Unknown = 20,
    };
    struct IBrushView;
    struct IBrushView2;
    struct IBrushViewFactory;
    struct ICircleView;
    struct ICircleViewManager;
    struct IClipPathView;
    struct IClipPathViewManager;
    struct ID2DBrush;
    struct ID2DDevice;
    struct ID2DDeviceContext;
    struct ID2DGeometry;
    struct IDefsView;
    struct IDefsViewManager;
    struct IEllipseView;
    struct IEllipseViewManager;
    struct IGroupView;
    struct IGroupView2;
    struct IGroupViewFactory;
    struct IGroupViewManager;
    struct IGroupViewManagerFactory;
    struct IImageView;
    struct IImageViewManager;
    struct ILineView;
    struct ILineViewManager;
    struct ILinearGradientView;
    struct ILinearGradientViewManager;
    struct IMarkerView;
    struct IMarkerViewManager;
    struct IMaskView;
    struct IMaskViewManager;
    struct IPathView;
    struct IPathViewManager;
    struct IPatternView;
    struct IPatternViewManager;
    struct IRadialGradientView;
    struct IRadialGradientViewManager;
    struct IReactPackageProvider;
    struct IRectView;
    struct IRectViewManager;
    struct IRenderable;
    struct IRenderablePaper;
    struct IRenderableView;
    struct IRenderableView2;
    struct IRenderableViewFactory;
    struct IRenderableViewManager;
    struct IRenderableViewManagerFactory;
    struct ISvgView;
    struct ISvgView2;
    struct ISvgViewFactory;
    struct ISvgViewManager;
    struct ISymbolView;
    struct ISymbolView2;
    struct ISymbolViewManager;
    struct ITSpanView;
    struct ITSpanView2;
    struct ITSpanViewManager;
    struct ITextView;
    struct ITextView2;
    struct ITextViewFactory;
    struct ITextViewManager;
    struct ITextViewManagerFactory;
    struct IUnsupportedSvgViewManager;
    struct IUnsupportedSvgViewManagerFactory;
    struct IUseView;
    struct IUseViewManager;
    struct BrushView;
    struct CircleView;
    struct CircleViewManager;
    struct ClipPathView;
    struct ClipPathViewManager;
    struct D2DBrush;
    struct D2DDevice;
    struct D2DDeviceContext;
    struct D2DGeometry;
    struct DefsView;
    struct DefsViewManager;
    struct EllipseView;
    struct EllipseViewManager;
    struct GroupView;
    struct GroupViewManager;
    struct ImageView;
    struct ImageViewManager;
    struct LineView;
    struct LineViewManager;
    struct LinearGradientView;
    struct LinearGradientViewManager;
    struct MarkerView;
    struct MarkerViewManager;
    struct MaskView;
    struct MaskViewManager;
    struct PathView;
    struct PathViewManager;
    struct PatternView;
    struct PatternViewManager;
    struct RadialGradientView;
    struct RadialGradientViewManager;
    struct ReactPackageProvider;
    struct RectView;
    struct RectViewManager;
    struct RenderableView;
    struct RenderableViewManager;
    struct SvgView;
    struct SvgViewManager;
    struct SymbolView;
    struct SymbolViewManager;
    struct TSpanView;
    struct TSpanViewManager;
    struct TextView;
    struct TextViewManager;
    struct UnsupportedSvgViewManager;
    struct UseView;
    struct UseViewManager;
    struct SVGLength;
}
namespace winrt::impl
{
    template <> struct category<winrt::RNSVG::IBrushView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IBrushView2>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IBrushViewFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ICircleView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ICircleViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IClipPathView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IClipPathViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ID2DBrush>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ID2DDevice>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ID2DDeviceContext>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ID2DGeometry>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IDefsView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IDefsViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IEllipseView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IEllipseViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IGroupView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IGroupView2>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IGroupViewFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IGroupViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IGroupViewManagerFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IImageView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IImageViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ILineView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ILineViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ILinearGradientView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ILinearGradientViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IMarkerView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IMarkerViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IMaskView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IMaskViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IPathView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IPathViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IPatternView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IPatternViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRadialGradientView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRadialGradientViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IReactPackageProvider>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRectView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRectViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRenderable>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRenderablePaper>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRenderableView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRenderableView2>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRenderableViewFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRenderableViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IRenderableViewManagerFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ISvgView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ISvgView2>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ISvgViewFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ISvgViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ISymbolView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ISymbolView2>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ISymbolViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ITSpanView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ITSpanView2>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ITSpanViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ITextView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ITextView2>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ITextViewFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ITextViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::ITextViewManagerFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IUnsupportedSvgViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IUnsupportedSvgViewManagerFactory>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IUseView>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::IUseViewManager>{ using type = interface_category; };
    template <> struct category<winrt::RNSVG::BrushView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::CircleView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::CircleViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::ClipPathView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::ClipPathViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::D2DBrush>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::D2DDevice>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::D2DDeviceContext>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::D2DGeometry>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::DefsView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::DefsViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::EllipseView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::EllipseViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::GroupView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::GroupViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::ImageView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::ImageViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::LineView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::LineViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::LinearGradientView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::LinearGradientViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::MarkerView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::MarkerViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::MaskView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::MaskViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::PathView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::PathViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::PatternView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::PatternViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::RadialGradientView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::RadialGradientViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::ReactPackageProvider>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::RectView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::RectViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::RenderableView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::RenderableViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::SvgView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::SvgViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::SymbolView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::SymbolViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::TSpanView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::TSpanViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::TextView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::TextViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::UnsupportedSvgViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::UseView>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::UseViewManager>{ using type = class_category; };
    template <> struct category<winrt::RNSVG::BaseProp>{ using type = enum_category; };
    template <> struct category<winrt::RNSVG::FillRule>{ using type = enum_category; };
    template <> struct category<winrt::RNSVG::FontProp>{ using type = enum_category; };
    template <> struct category<winrt::RNSVG::LengthType>{ using type = enum_category; };
    template <> struct category<winrt::RNSVG::LineCap>{ using type = enum_category; };
    template <> struct category<winrt::RNSVG::LineJoin>{ using type = enum_category; };
    template <> struct category<winrt::RNSVG::MeetOrSlice>{ using type = enum_category; };
    template <> struct category<winrt::RNSVG::SVGClass>{ using type = enum_category; };
    template <> struct category<winrt::RNSVG::SVGLength>{ using type = struct_category<float, winrt::RNSVG::LengthType>; };
    template <> inline constexpr auto& name_v<winrt::RNSVG::BrushView> = L"RNSVG.BrushView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::CircleView> = L"RNSVG.CircleView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::CircleViewManager> = L"RNSVG.CircleViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ClipPathView> = L"RNSVG.ClipPathView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ClipPathViewManager> = L"RNSVG.ClipPathViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::D2DBrush> = L"RNSVG.D2DBrush";
    template <> inline constexpr auto& name_v<winrt::RNSVG::D2DDevice> = L"RNSVG.D2DDevice";
    template <> inline constexpr auto& name_v<winrt::RNSVG::D2DDeviceContext> = L"RNSVG.D2DDeviceContext";
    template <> inline constexpr auto& name_v<winrt::RNSVG::D2DGeometry> = L"RNSVG.D2DGeometry";
    template <> inline constexpr auto& name_v<winrt::RNSVG::DefsView> = L"RNSVG.DefsView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::DefsViewManager> = L"RNSVG.DefsViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::EllipseView> = L"RNSVG.EllipseView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::EllipseViewManager> = L"RNSVG.EllipseViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::GroupView> = L"RNSVG.GroupView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::GroupViewManager> = L"RNSVG.GroupViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ImageView> = L"RNSVG.ImageView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ImageViewManager> = L"RNSVG.ImageViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::LineView> = L"RNSVG.LineView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::LineViewManager> = L"RNSVG.LineViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::LinearGradientView> = L"RNSVG.LinearGradientView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::LinearGradientViewManager> = L"RNSVG.LinearGradientViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::MarkerView> = L"RNSVG.MarkerView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::MarkerViewManager> = L"RNSVG.MarkerViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::MaskView> = L"RNSVG.MaskView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::MaskViewManager> = L"RNSVG.MaskViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::PathView> = L"RNSVG.PathView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::PathViewManager> = L"RNSVG.PathViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::PatternView> = L"RNSVG.PatternView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::PatternViewManager> = L"RNSVG.PatternViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::RadialGradientView> = L"RNSVG.RadialGradientView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::RadialGradientViewManager> = L"RNSVG.RadialGradientViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ReactPackageProvider> = L"RNSVG.ReactPackageProvider";
    template <> inline constexpr auto& name_v<winrt::RNSVG::RectView> = L"RNSVG.RectView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::RectViewManager> = L"RNSVG.RectViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::RenderableView> = L"RNSVG.RenderableView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::RenderableViewManager> = L"RNSVG.RenderableViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::SvgView> = L"RNSVG.SvgView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::SvgViewManager> = L"RNSVG.SvgViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::SymbolView> = L"RNSVG.SymbolView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::SymbolViewManager> = L"RNSVG.SymbolViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::TSpanView> = L"RNSVG.TSpanView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::TSpanViewManager> = L"RNSVG.TSpanViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::TextView> = L"RNSVG.TextView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::TextViewManager> = L"RNSVG.TextViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::UnsupportedSvgViewManager> = L"RNSVG.UnsupportedSvgViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::UseView> = L"RNSVG.UseView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::UseViewManager> = L"RNSVG.UseViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::BaseProp> = L"RNSVG.BaseProp";
    template <> inline constexpr auto& name_v<winrt::RNSVG::FillRule> = L"RNSVG.FillRule";
    template <> inline constexpr auto& name_v<winrt::RNSVG::FontProp> = L"RNSVG.FontProp";
    template <> inline constexpr auto& name_v<winrt::RNSVG::LengthType> = L"RNSVG.LengthType";
    template <> inline constexpr auto& name_v<winrt::RNSVG::LineCap> = L"RNSVG.LineCap";
    template <> inline constexpr auto& name_v<winrt::RNSVG::LineJoin> = L"RNSVG.LineJoin";
    template <> inline constexpr auto& name_v<winrt::RNSVG::MeetOrSlice> = L"RNSVG.MeetOrSlice";
    template <> inline constexpr auto& name_v<winrt::RNSVG::SVGClass> = L"RNSVG.SVGClass";
    template <> inline constexpr auto& name_v<winrt::RNSVG::SVGLength> = L"RNSVG.SVGLength";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IBrushView> = L"RNSVG.IBrushView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IBrushView2> = L"RNSVG.IBrushView2";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IBrushViewFactory> = L"RNSVG.IBrushViewFactory";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ICircleView> = L"RNSVG.ICircleView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ICircleViewManager> = L"RNSVG.ICircleViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IClipPathView> = L"RNSVG.IClipPathView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IClipPathViewManager> = L"RNSVG.IClipPathViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ID2DBrush> = L"RNSVG.ID2DBrush";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ID2DDevice> = L"RNSVG.ID2DDevice";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ID2DDeviceContext> = L"RNSVG.ID2DDeviceContext";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ID2DGeometry> = L"RNSVG.ID2DGeometry";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IDefsView> = L"RNSVG.IDefsView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IDefsViewManager> = L"RNSVG.IDefsViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IEllipseView> = L"RNSVG.IEllipseView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IEllipseViewManager> = L"RNSVG.IEllipseViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IGroupView> = L"RNSVG.IGroupView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IGroupView2> = L"RNSVG.IGroupView2";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IGroupViewFactory> = L"RNSVG.IGroupViewFactory";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IGroupViewManager> = L"RNSVG.IGroupViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IGroupViewManagerFactory> = L"RNSVG.IGroupViewManagerFactory";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IImageView> = L"RNSVG.IImageView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IImageViewManager> = L"RNSVG.IImageViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ILineView> = L"RNSVG.ILineView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ILineViewManager> = L"RNSVG.ILineViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ILinearGradientView> = L"RNSVG.ILinearGradientView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ILinearGradientViewManager> = L"RNSVG.ILinearGradientViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IMarkerView> = L"RNSVG.IMarkerView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IMarkerViewManager> = L"RNSVG.IMarkerViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IMaskView> = L"RNSVG.IMaskView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IMaskViewManager> = L"RNSVG.IMaskViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IPathView> = L"RNSVG.IPathView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IPathViewManager> = L"RNSVG.IPathViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IPatternView> = L"RNSVG.IPatternView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IPatternViewManager> = L"RNSVG.IPatternViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRadialGradientView> = L"RNSVG.IRadialGradientView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRadialGradientViewManager> = L"RNSVG.IRadialGradientViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IReactPackageProvider> = L"RNSVG.IReactPackageProvider";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRectView> = L"RNSVG.IRectView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRectViewManager> = L"RNSVG.IRectViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRenderable> = L"RNSVG.IRenderable";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRenderablePaper> = L"RNSVG.IRenderablePaper";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRenderableView> = L"RNSVG.IRenderableView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRenderableView2> = L"RNSVG.IRenderableView2";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRenderableViewFactory> = L"RNSVG.IRenderableViewFactory";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRenderableViewManager> = L"RNSVG.IRenderableViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IRenderableViewManagerFactory> = L"RNSVG.IRenderableViewManagerFactory";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ISvgView> = L"RNSVG.ISvgView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ISvgView2> = L"RNSVG.ISvgView2";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ISvgViewFactory> = L"RNSVG.ISvgViewFactory";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ISvgViewManager> = L"RNSVG.ISvgViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ISymbolView> = L"RNSVG.ISymbolView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ISymbolView2> = L"RNSVG.ISymbolView2";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ISymbolViewManager> = L"RNSVG.ISymbolViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ITSpanView> = L"RNSVG.ITSpanView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ITSpanView2> = L"RNSVG.ITSpanView2";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ITSpanViewManager> = L"RNSVG.ITSpanViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ITextView> = L"RNSVG.ITextView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ITextView2> = L"RNSVG.ITextView2";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ITextViewFactory> = L"RNSVG.ITextViewFactory";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ITextViewManager> = L"RNSVG.ITextViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::ITextViewManagerFactory> = L"RNSVG.ITextViewManagerFactory";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IUnsupportedSvgViewManager> = L"RNSVG.IUnsupportedSvgViewManager";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IUnsupportedSvgViewManagerFactory> = L"RNSVG.IUnsupportedSvgViewManagerFactory";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IUseView> = L"RNSVG.IUseView";
    template <> inline constexpr auto& name_v<winrt::RNSVG::IUseViewManager> = L"RNSVG.IUseViewManager";
    template <> inline constexpr guid guid_v<winrt::RNSVG::IBrushView>{ 0x36EA3630,0xB790,0x5B50,{ 0x84,0xC0,0xEF,0x86,0xF0,0xF8,0xDD,0x8B } }; // 36EA3630-B790-5B50-84C0-EF86F0F8DD8B
    template <> inline constexpr guid guid_v<winrt::RNSVG::IBrushView2>{ 0xD6CAD208,0x37F2,0x52EC,{ 0x84,0xBD,0x46,0xA6,0xB5,0x1F,0x73,0xB0 } }; // D6CAD208-37F2-52EC-84BD-46A6B51F73B0
    template <> inline constexpr guid guid_v<winrt::RNSVG::IBrushViewFactory>{ 0x20D97262,0x266C,0x506C,{ 0xBC,0x10,0xEA,0x47,0x6D,0x8B,0xA5,0xE9 } }; // 20D97262-266C-506C-BC10-EA476D8BA5E9
    template <> inline constexpr guid guid_v<winrt::RNSVG::ICircleView>{ 0x23E8E6DA,0x8187,0x5806,{ 0x8C,0x2F,0xBC,0x9D,0xF3,0xA4,0x09,0x80 } }; // 23E8E6DA-8187-5806-8C2F-BC9DF3A40980
    template <> inline constexpr guid guid_v<winrt::RNSVG::ICircleViewManager>{ 0x09E1BD06,0x855E,0x5FC7,{ 0xA3,0xB3,0x7E,0x57,0x4D,0x46,0x87,0x76 } }; // 09E1BD06-855E-5FC7-A3B3-7E574D468776
    template <> inline constexpr guid guid_v<winrt::RNSVG::IClipPathView>{ 0xD55261C2,0x8BCF,0x53F0,{ 0x93,0xAA,0xCA,0xAC,0x0A,0x33,0x70,0x7D } }; // D55261C2-8BCF-53F0-93AA-CAAC0A33707D
    template <> inline constexpr guid guid_v<winrt::RNSVG::IClipPathViewManager>{ 0xBB422CA3,0xA8F7,0x5D20,{ 0x88,0x59,0x30,0x61,0x7D,0x9C,0xF8,0x69 } }; // BB422CA3-A8F7-5D20-8859-30617D9CF869
    template <> inline constexpr guid guid_v<winrt::RNSVG::ID2DBrush>{ 0x1E2583D0,0x5272,0x5DB3,{ 0x8C,0xE1,0xEB,0x28,0xBC,0xC3,0x45,0x3B } }; // 1E2583D0-5272-5DB3-8CE1-EB28BCC3453B
    template <> inline constexpr guid guid_v<winrt::RNSVG::ID2DDevice>{ 0xA05C0C4A,0xC391,0x5DB6,{ 0x8C,0xFC,0x45,0x12,0x3E,0x61,0x9D,0x12 } }; // A05C0C4A-C391-5DB6-8CFC-45123E619D12
    template <> inline constexpr guid guid_v<winrt::RNSVG::ID2DDeviceContext>{ 0x9CE7BD44,0x0F48,0x50E0,{ 0x84,0x54,0xA7,0x50,0x58,0x92,0xB6,0x7E } }; // 9CE7BD44-0F48-50E0-8454-A7505892B67E
    template <> inline constexpr guid guid_v<winrt::RNSVG::ID2DGeometry>{ 0x7FAA4B66,0xB4F7,0x5D8F,{ 0xBF,0x2D,0x54,0x06,0xF2,0x88,0xE3,0x57 } }; // 7FAA4B66-B4F7-5D8F-BF2D-5406F288E357
    template <> inline constexpr guid guid_v<winrt::RNSVG::IDefsView>{ 0xED9C62A2,0xF935,0x5154,{ 0x84,0x3E,0x20,0x4F,0x72,0xF5,0xC4,0xD1 } }; // ED9C62A2-F935-5154-843E-204F72F5C4D1
    template <> inline constexpr guid guid_v<winrt::RNSVG::IDefsViewManager>{ 0xA92E67C2,0x89DF,0x5076,{ 0x90,0x56,0x80,0xC0,0x38,0xE5,0xE4,0x03 } }; // A92E67C2-89DF-5076-9056-80C038E5E403
    template <> inline constexpr guid guid_v<winrt::RNSVG::IEllipseView>{ 0x59C6CC25,0x2507,0x56B6,{ 0x8B,0xC8,0x8A,0xFB,0x6D,0xAC,0x01,0x30 } }; // 59C6CC25-2507-56B6-8BC8-8AFB6DAC0130
    template <> inline constexpr guid guid_v<winrt::RNSVG::IEllipseViewManager>{ 0x7AE6FA97,0x543F,0x5EEA,{ 0x95,0x3B,0xEE,0x78,0x39,0x94,0xE2,0x06 } }; // 7AE6FA97-543F-5EEA-953B-EE783994E206
    template <> inline constexpr guid guid_v<winrt::RNSVG::IGroupView>{ 0x15EAB8B8,0x54F2,0x5D62,{ 0x80,0x3A,0xE2,0x05,0xF9,0x1B,0xE8,0x2F } }; // 15EAB8B8-54F2-5D62-803A-E205F91BE82F
    template <> inline constexpr guid guid_v<winrt::RNSVG::IGroupView2>{ 0xBB72A87E,0x5645,0x5CF1,{ 0x84,0x14,0xFD,0x26,0x0E,0x21,0x69,0x92 } }; // BB72A87E-5645-5CF1-8414-FD260E216992
    template <> inline constexpr guid guid_v<winrt::RNSVG::IGroupViewFactory>{ 0xEB59ECBA,0x65DC,0x5F5E,{ 0xB3,0xF5,0x88,0x32,0xC0,0xA7,0x46,0x3C } }; // EB59ECBA-65DC-5F5E-B3F5-8832C0A7463C
    template <> inline constexpr guid guid_v<winrt::RNSVG::IGroupViewManager>{ 0x2EE236C3,0x0846,0x53D4,{ 0xA6,0x3C,0x9D,0x6F,0x58,0x6D,0x84,0x29 } }; // 2EE236C3-0846-53D4-A63C-9D6F586D8429
    template <> inline constexpr guid guid_v<winrt::RNSVG::IGroupViewManagerFactory>{ 0x88F7E139,0xFE65,0x5D23,{ 0x9C,0xAC,0xD8,0xA9,0x98,0x87,0x39,0xC5 } }; // 88F7E139-FE65-5D23-9CAC-D8A9988739C5
    template <> inline constexpr guid guid_v<winrt::RNSVG::IImageView>{ 0xF4342496,0x1961,0x564F,{ 0x99,0xC3,0x22,0xA6,0x0B,0x65,0x6F,0x0D } }; // F4342496-1961-564F-99C3-22A60B656F0D
    template <> inline constexpr guid guid_v<winrt::RNSVG::IImageViewManager>{ 0x974DE8E9,0x00D3,0x57F2,{ 0x8C,0x1C,0x35,0xF2,0x09,0x6F,0x8E,0xB4 } }; // 974DE8E9-00D3-57F2-8C1C-35F2096F8EB4
    template <> inline constexpr guid guid_v<winrt::RNSVG::ILineView>{ 0xB0821995,0x70F4,0x5F2B,{ 0xAE,0xCC,0x00,0xCC,0xED,0x57,0x29,0x18 } }; // B0821995-70F4-5F2B-AECC-00CCED572918
    template <> inline constexpr guid guid_v<winrt::RNSVG::ILineViewManager>{ 0x2ABE9C69,0x000D,0x5004,{ 0xA9,0x34,0x0F,0x3D,0xB6,0x20,0x23,0x4C } }; // 2ABE9C69-000D-5004-A934-0F3DB620234C
    template <> inline constexpr guid guid_v<winrt::RNSVG::ILinearGradientView>{ 0x6918801E,0x2837,0x5296,{ 0x89,0xED,0x6B,0x85,0xD1,0xCB,0x05,0xF1 } }; // 6918801E-2837-5296-89ED-6B85D1CB05F1
    template <> inline constexpr guid guid_v<winrt::RNSVG::ILinearGradientViewManager>{ 0x75B01FC3,0x50DA,0x5360,{ 0x9A,0xD4,0xA5,0x26,0x13,0x39,0xA5,0xD1 } }; // 75B01FC3-50DA-5360-9AD4-A5261339A5D1
    template <> inline constexpr guid guid_v<winrt::RNSVG::IMarkerView>{ 0x4FDBC7B7,0xD856,0x51D6,{ 0x97,0x30,0xA0,0x37,0xA1,0x8B,0x62,0x69 } }; // 4FDBC7B7-D856-51D6-9730-A037A18B6269
    template <> inline constexpr guid guid_v<winrt::RNSVG::IMarkerViewManager>{ 0x60EABA9C,0x4FE3,0x5E88,{ 0x8F,0xF2,0xDF,0x81,0xF3,0xE2,0xE4,0xF7 } }; // 60EABA9C-4FE3-5E88-8FF2-DF81F3E2E4F7
    template <> inline constexpr guid guid_v<winrt::RNSVG::IMaskView>{ 0x3CEF273B,0x8EA1,0x5044,{ 0x95,0x8F,0x1A,0x1E,0x50,0x01,0x34,0xCE } }; // 3CEF273B-8EA1-5044-958F-1A1E500134CE
    template <> inline constexpr guid guid_v<winrt::RNSVG::IMaskViewManager>{ 0xE0A6F94C,0x31E9,0x584D,{ 0x8F,0x2A,0x2A,0x27,0xD8,0x36,0xD4,0xDD } }; // E0A6F94C-31E9-584D-8F2A-2A27D836D4DD
    template <> inline constexpr guid guid_v<winrt::RNSVG::IPathView>{ 0x42CA0304,0x3A2E,0x5BB4,{ 0xB3,0x65,0x9F,0x13,0xAE,0x61,0xCA,0x50 } }; // 42CA0304-3A2E-5BB4-B365-9F13AE61CA50
    template <> inline constexpr guid guid_v<winrt::RNSVG::IPathViewManager>{ 0x688EAAAC,0x0D2F,0x5AE2,{ 0x92,0x82,0x1B,0x82,0x68,0x0D,0x13,0x2B } }; // 688EAAAC-0D2F-5AE2-9282-1B82680D132B
    template <> inline constexpr guid guid_v<winrt::RNSVG::IPatternView>{ 0xDECDA618,0x6C89,0x55DF,{ 0xA0,0xC6,0x2B,0xD2,0x73,0x1B,0x0A,0xA4 } }; // DECDA618-6C89-55DF-A0C6-2BD2731B0AA4
    template <> inline constexpr guid guid_v<winrt::RNSVG::IPatternViewManager>{ 0xAADF65A4,0xB725,0x5618,{ 0x82,0x0E,0xC5,0x1E,0xBC,0x91,0x29,0xDF } }; // AADF65A4-B725-5618-820E-C51EBC9129DF
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRadialGradientView>{ 0x7E05091E,0xE0C9,0x51D3,{ 0x8E,0xA0,0x11,0x40,0xBB,0xB3,0x5E,0xEC } }; // 7E05091E-E0C9-51D3-8EA0-1140BBB35EEC
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRadialGradientViewManager>{ 0x95942569,0x8E83,0x507F,{ 0x8C,0x10,0x7F,0x8C,0x95,0x9F,0xA1,0xF1 } }; // 95942569-8E83-507F-8C10-7F8C959FA1F1
    template <> inline constexpr guid guid_v<winrt::RNSVG::IReactPackageProvider>{ 0x614D2524,0xE02A,0x5364,{ 0xBD,0x52,0x5E,0xBA,0xF2,0x2A,0x65,0xF7 } }; // 614D2524-E02A-5364-BD52-5EBAF22A65F7
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRectView>{ 0xB3074326,0x0A1B,0x56C1,{ 0x8A,0xD0,0x0F,0x6A,0x7E,0x5D,0xBD,0xC7 } }; // B3074326-0A1B-56C1-8AD0-0F6A7E5DBDC7
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRectViewManager>{ 0xA9FDA99E,0xB56D,0x5118,{ 0x98,0x71,0x6E,0xDE,0xAA,0xE4,0x11,0x4A } }; // A9FDA99E-B56D-5118-9871-6EDEAAE4114A
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRenderable>{ 0x269EE74F,0x43D2,0x5E01,{ 0x9B,0x3E,0xCA,0xD8,0x38,0x19,0xBD,0x1E } }; // 269EE74F-43D2-5E01-9B3E-CAD83819BD1E
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRenderablePaper>{ 0x04391CB7,0x933E,0x5D3B,{ 0xA2,0x0F,0x92,0xF4,0x7B,0xDB,0x49,0x25 } }; // 04391CB7-933E-5D3B-A20F-92F47BDB4925
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRenderableView>{ 0x6C87B26B,0x1E20,0x5E28,{ 0x8E,0xFA,0xEA,0xD3,0x2D,0xB5,0x0F,0x00 } }; // 6C87B26B-1E20-5E28-8EFA-EAD32DB50F00
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRenderableView2>{ 0x4D7FAF76,0xD5B6,0x5905,{ 0xB3,0x56,0x00,0xF8,0xEB,0x2A,0x6F,0x46 } }; // 4D7FAF76-D5B6-5905-B356-00F8EB2A6F46
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRenderableViewFactory>{ 0xEA5D774F,0x482E,0x5F51,{ 0x81,0x35,0x4D,0x3A,0xA1,0xFF,0x89,0x8E } }; // EA5D774F-482E-5F51-8135-4D3AA1FF898E
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRenderableViewManager>{ 0x41FA152F,0x9D96,0x54CB,{ 0x80,0xA8,0x50,0xB9,0x2F,0x58,0x14,0xB4 } }; // 41FA152F-9D96-54CB-80A8-50B92F5814B4
    template <> inline constexpr guid guid_v<winrt::RNSVG::IRenderableViewManagerFactory>{ 0x637E840F,0xDD7F,0x5A82,{ 0xA2,0x86,0xD2,0xAD,0x94,0x8E,0x90,0xEB } }; // 637E840F-DD7F-5A82-A286-D2AD948E90EB
    template <> inline constexpr guid guid_v<winrt::RNSVG::ISvgView>{ 0xD1329C0A,0xF867,0x51C0,{ 0x80,0xF4,0x56,0x83,0xEF,0x2C,0x0E,0x26 } }; // D1329C0A-F867-51C0-80F4-5683EF2C0E26
    template <> inline constexpr guid guid_v<winrt::RNSVG::ISvgView2>{ 0xE17AD153,0xF75E,0x58C4,{ 0xA8,0xBB,0x20,0x72,0x29,0x7F,0x4E,0x7F } }; // E17AD153-F75E-58C4-A8BB-2072297F4E7F
    template <> inline constexpr guid guid_v<winrt::RNSVG::ISvgViewFactory>{ 0xBBDACC9C,0xBC73,0x567B,{ 0x9F,0xB2,0x41,0xF1,0x51,0xE1,0xA8,0xC5 } }; // BBDACC9C-BC73-567B-9FB2-41F151E1A8C5
    template <> inline constexpr guid guid_v<winrt::RNSVG::ISvgViewManager>{ 0x91E37AFF,0x3148,0x52EB,{ 0xA1,0x5A,0x7D,0xF4,0xDA,0x90,0xDF,0x66 } }; // 91E37AFF-3148-52EB-A15A-7DF4DA90DF66
    template <> inline constexpr guid guid_v<winrt::RNSVG::ISymbolView>{ 0xC716E7A3,0xCCCD,0x5E22,{ 0x88,0x08,0x78,0x25,0xD9,0xE4,0x14,0x11 } }; // C716E7A3-CCCD-5E22-8808-7825D9E41411
    template <> inline constexpr guid guid_v<winrt::RNSVG::ISymbolView2>{ 0x52418DEA,0xBB23,0x5F7A,{ 0x96,0xEB,0xE1,0x21,0xE9,0x56,0x92,0xF4 } }; // 52418DEA-BB23-5F7A-96EB-E121E95692F4
    template <> inline constexpr guid guid_v<winrt::RNSVG::ISymbolViewManager>{ 0x40C2226B,0xD0D5,0x510F,{ 0xA3,0x87,0x41,0x63,0xD3,0x99,0xF2,0xD4 } }; // 40C2226B-D0D5-510F-A387-4163D399F2D4
    template <> inline constexpr guid guid_v<winrt::RNSVG::ITSpanView>{ 0x9593F858,0x4E50,0x5E95,{ 0xBC,0x91,0x0D,0x16,0x2A,0x01,0x20,0xF7 } }; // 9593F858-4E50-5E95-BC91-0D162A0120F7
    template <> inline constexpr guid guid_v<winrt::RNSVG::ITSpanView2>{ 0x461FD2D5,0x3ECC,0x5A42,{ 0xB7,0xCB,0x80,0x52,0xB3,0xD1,0xE9,0x04 } }; // 461FD2D5-3ECC-5A42-B7CB-8052B3D1E904
    template <> inline constexpr guid guid_v<winrt::RNSVG::ITSpanViewManager>{ 0x7E6EF8C5,0xCAC9,0x5C73,{ 0x91,0x50,0x6A,0x91,0xF8,0x7D,0x13,0x3B } }; // 7E6EF8C5-CAC9-5C73-9150-6A91F87D133B
    template <> inline constexpr guid guid_v<winrt::RNSVG::ITextView>{ 0xFD296BD9,0x803F,0x5A5D,{ 0xA6,0x09,0x7D,0x72,0x09,0x53,0x02,0x5E } }; // FD296BD9-803F-5A5D-A609-7D720953025E
    template <> inline constexpr guid guid_v<winrt::RNSVG::ITextView2>{ 0x03FF8FA7,0xFB9C,0x56DD,{ 0x93,0x04,0x59,0x61,0x9A,0x77,0x53,0xD2 } }; // 03FF8FA7-FB9C-56DD-9304-59619A7753D2
    template <> inline constexpr guid guid_v<winrt::RNSVG::ITextViewFactory>{ 0x54E997F8,0x29BF,0x5704,{ 0x90,0x6A,0xBE,0xF0,0x6E,0x20,0x1A,0x42 } }; // 54E997F8-29BF-5704-906A-BEF06E201A42
    template <> inline constexpr guid guid_v<winrt::RNSVG::ITextViewManager>{ 0x37B718C9,0xEE5D,0x5123,{ 0x81,0xAB,0x61,0xD1,0x83,0x2C,0x59,0x2E } }; // 37B718C9-EE5D-5123-81AB-61D1832C592E
    template <> inline constexpr guid guid_v<winrt::RNSVG::ITextViewManagerFactory>{ 0x6A14B745,0xE9E8,0x5EAD,{ 0x81,0xF0,0x4A,0x07,0x54,0x35,0x87,0xF2 } }; // 6A14B745-E9E8-5EAD-81F0-4A07543587F2
    template <> inline constexpr guid guid_v<winrt::RNSVG::IUnsupportedSvgViewManager>{ 0x038B330B,0xB7C1,0x5F02,{ 0xA4,0xA5,0x7B,0x51,0x4C,0x8F,0xA6,0x14 } }; // 038B330B-B7C1-5F02-A4A5-7B514C8FA614
    template <> inline constexpr guid guid_v<winrt::RNSVG::IUnsupportedSvgViewManagerFactory>{ 0xA4A96387,0x30E8,0x57EE,{ 0x8B,0xF5,0x0A,0x53,0xEA,0xA2,0x14,0x20 } }; // A4A96387-30E8-57EE-8BF5-0A53EAA21420
    template <> inline constexpr guid guid_v<winrt::RNSVG::IUseView>{ 0xEE6B72B6,0x6B0D,0x5F0F,{ 0x88,0x72,0x3A,0xF5,0xF2,0xBB,0x90,0xD8 } }; // EE6B72B6-6B0D-5F0F-8872-3AF5F2BB90D8
    template <> inline constexpr guid guid_v<winrt::RNSVG::IUseViewManager>{ 0x8CAEF498,0xCD14,0x557A,{ 0xB7,0xFF,0xD8,0xAB,0xFB,0xF1,0x75,0xFB } }; // 8CAEF498-CD14-557A-B7FF-D8ABFBF175FB
    template <> struct default_interface<winrt::RNSVG::BrushView>{ using type = winrt::RNSVG::IBrushView2; };
    template <> struct default_interface<winrt::RNSVG::CircleView>{ using type = winrt::RNSVG::ICircleView; };
    template <> struct default_interface<winrt::RNSVG::CircleViewManager>{ using type = winrt::RNSVG::ICircleViewManager; };
    template <> struct default_interface<winrt::RNSVG::ClipPathView>{ using type = winrt::RNSVG::IClipPathView; };
    template <> struct default_interface<winrt::RNSVG::ClipPathViewManager>{ using type = winrt::RNSVG::IClipPathViewManager; };
    template <> struct default_interface<winrt::RNSVG::D2DBrush>{ using type = winrt::RNSVG::ID2DBrush; };
    template <> struct default_interface<winrt::RNSVG::D2DDevice>{ using type = winrt::RNSVG::ID2DDevice; };
    template <> struct default_interface<winrt::RNSVG::D2DDeviceContext>{ using type = winrt::RNSVG::ID2DDeviceContext; };
    template <> struct default_interface<winrt::RNSVG::D2DGeometry>{ using type = winrt::RNSVG::ID2DGeometry; };
    template <> struct default_interface<winrt::RNSVG::DefsView>{ using type = winrt::RNSVG::IDefsView; };
    template <> struct default_interface<winrt::RNSVG::DefsViewManager>{ using type = winrt::RNSVG::IDefsViewManager; };
    template <> struct default_interface<winrt::RNSVG::EllipseView>{ using type = winrt::RNSVG::IEllipseView; };
    template <> struct default_interface<winrt::RNSVG::EllipseViewManager>{ using type = winrt::RNSVG::IEllipseViewManager; };
    template <> struct default_interface<winrt::RNSVG::GroupView>{ using type = winrt::RNSVG::IGroupView2; };
    template <> struct default_interface<winrt::RNSVG::GroupViewManager>{ using type = winrt::RNSVG::IGroupViewManager; };
    template <> struct default_interface<winrt::RNSVG::ImageView>{ using type = winrt::RNSVG::IImageView; };
    template <> struct default_interface<winrt::RNSVG::ImageViewManager>{ using type = winrt::RNSVG::IImageViewManager; };
    template <> struct default_interface<winrt::RNSVG::LineView>{ using type = winrt::RNSVG::ILineView; };
    template <> struct default_interface<winrt::RNSVG::LineViewManager>{ using type = winrt::RNSVG::ILineViewManager; };
    template <> struct default_interface<winrt::RNSVG::LinearGradientView>{ using type = winrt::RNSVG::ILinearGradientView; };
    template <> struct default_interface<winrt::RNSVG::LinearGradientViewManager>{ using type = winrt::RNSVG::ILinearGradientViewManager; };
    template <> struct default_interface<winrt::RNSVG::MarkerView>{ using type = winrt::RNSVG::IMarkerView; };
    template <> struct default_interface<winrt::RNSVG::MarkerViewManager>{ using type = winrt::RNSVG::IMarkerViewManager; };
    template <> struct default_interface<winrt::RNSVG::MaskView>{ using type = winrt::RNSVG::IMaskView; };
    template <> struct default_interface<winrt::RNSVG::MaskViewManager>{ using type = winrt::RNSVG::IMaskViewManager; };
    template <> struct default_interface<winrt::RNSVG::PathView>{ using type = winrt::RNSVG::IPathView; };
    template <> struct default_interface<winrt::RNSVG::PathViewManager>{ using type = winrt::RNSVG::IPathViewManager; };
    template <> struct default_interface<winrt::RNSVG::PatternView>{ using type = winrt::RNSVG::IPatternView; };
    template <> struct default_interface<winrt::RNSVG::PatternViewManager>{ using type = winrt::RNSVG::IPatternViewManager; };
    template <> struct default_interface<winrt::RNSVG::RadialGradientView>{ using type = winrt::RNSVG::IRadialGradientView; };
    template <> struct default_interface<winrt::RNSVG::RadialGradientViewManager>{ using type = winrt::RNSVG::IRadialGradientViewManager; };
    template <> struct default_interface<winrt::RNSVG::ReactPackageProvider>{ using type = winrt::RNSVG::IReactPackageProvider; };
    template <> struct default_interface<winrt::RNSVG::RectView>{ using type = winrt::RNSVG::IRectView; };
    template <> struct default_interface<winrt::RNSVG::RectViewManager>{ using type = winrt::RNSVG::IRectViewManager; };
    template <> struct default_interface<winrt::RNSVG::RenderableView>{ using type = winrt::RNSVG::IRenderableView2; };
    template <> struct default_interface<winrt::RNSVG::RenderableViewManager>{ using type = winrt::RNSVG::IRenderableViewManager; };
    template <> struct default_interface<winrt::RNSVG::SvgView>{ using type = winrt::RNSVG::ISvgView2; };
    template <> struct default_interface<winrt::RNSVG::SvgViewManager>{ using type = winrt::RNSVG::ISvgViewManager; };
    template <> struct default_interface<winrt::RNSVG::SymbolView>{ using type = winrt::RNSVG::ISymbolView2; };
    template <> struct default_interface<winrt::RNSVG::SymbolViewManager>{ using type = winrt::RNSVG::ISymbolViewManager; };
    template <> struct default_interface<winrt::RNSVG::TSpanView>{ using type = winrt::RNSVG::ITSpanView2; };
    template <> struct default_interface<winrt::RNSVG::TSpanViewManager>{ using type = winrt::RNSVG::ITSpanViewManager; };
    template <> struct default_interface<winrt::RNSVG::TextView>{ using type = winrt::RNSVG::ITextView2; };
    template <> struct default_interface<winrt::RNSVG::TextViewManager>{ using type = winrt::RNSVG::ITextViewManager; };
    template <> struct default_interface<winrt::RNSVG::UnsupportedSvgViewManager>{ using type = winrt::RNSVG::IUnsupportedSvgViewManager; };
    template <> struct default_interface<winrt::RNSVG::UseView>{ using type = winrt::RNSVG::IUseView; };
    template <> struct default_interface<winrt::RNSVG::UseViewManager>{ using type = winrt::RNSVG::IUseViewManager; };
    template <> struct abi<winrt::RNSVG::IBrushView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_Brush(void**) noexcept = 0;
            virtual int32_t __stdcall CreateBrush() noexcept = 0;
            virtual int32_t __stdcall SetBounds(winrt::Windows::Foundation::Rect) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IBrushView2>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IBrushViewFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::ICircleView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ICircleViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IClipPathView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IClipPathViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ID2DBrush>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ID2DDevice>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ID2DDeviceContext>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ID2DGeometry>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IDefsView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IDefsViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IEllipseView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IEllipseViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IGroupView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_FontSize(float*) noexcept = 0;
            virtual int32_t __stdcall put_FontSize(float) noexcept = 0;
            virtual int32_t __stdcall get_FontFamily(void**) noexcept = 0;
            virtual int32_t __stdcall put_FontFamily(void*) noexcept = 0;
            virtual int32_t __stdcall get_FontWeight(void**) noexcept = 0;
            virtual int32_t __stdcall put_FontWeight(void*) noexcept = 0;
            virtual int32_t __stdcall DrawGroup(void*, winrt::Windows::Foundation::Size) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IGroupView2>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_Children(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IGroupViewFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void*, void**, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IGroupViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IGroupViewManagerFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IImageView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IImageViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ILineView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ILineViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ILinearGradientView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ILinearGradientViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IMarkerView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IMarkerViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IMaskView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IMaskViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IPathView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IPathViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IPatternView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IPatternViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IRadialGradientView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IRadialGradientViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IReactPackageProvider>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IRectView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IRectViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IRenderable>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_Geometry(void**) noexcept = 0;
            virtual int32_t __stdcall put_Geometry(void*) noexcept = 0;
            virtual int32_t __stdcall get_IsResponsible(bool*) noexcept = 0;
            virtual int32_t __stdcall put_IsResponsible(bool) noexcept = 0;
            virtual int32_t __stdcall CreateResources() noexcept = 0;
            virtual int32_t __stdcall Draw(void*, winrt::Windows::Foundation::Size) noexcept = 0;
            virtual int32_t __stdcall MergeProperties(void*) noexcept = 0;
            virtual int32_t __stdcall SaveDefinition() noexcept = 0;
            virtual int32_t __stdcall Unload() noexcept = 0;
            virtual int32_t __stdcall CreateGeometry(void*) noexcept = 0;
            virtual int32_t __stdcall HitTest(winrt::Windows::Foundation::Point, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IRenderablePaper>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_SvgParent(void**) noexcept = 0;
            virtual int32_t __stdcall put_SvgParent(void*) noexcept = 0;
            virtual int32_t __stdcall UpdateProperties(void*, bool, bool) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IRenderableView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_IsUnloaded(bool*) noexcept = 0;
            virtual int32_t __stdcall get_Id(void**) noexcept = 0;
            virtual int32_t __stdcall get_SvgTransform(winrt::Windows::Foundation::Numerics::float3x2*) noexcept = 0;
            virtual int32_t __stdcall get_FillOpacity(float*) noexcept = 0;
            virtual int32_t __stdcall get_FillBrushId(void**) noexcept = 0;
            virtual int32_t __stdcall get_StrokeOpacity(float*) noexcept = 0;
            virtual int32_t __stdcall get_StrokeBrushId(void**) noexcept = 0;
            virtual int32_t __stdcall get_StrokeWidth(struct struct_RNSVG_SVGLength*) noexcept = 0;
            virtual int32_t __stdcall get_StrokeMiterLimit(float*) noexcept = 0;
            virtual int32_t __stdcall get_StrokeDashOffset(float*) noexcept = 0;
            virtual int32_t __stdcall get_StrokeDashArray(void**) noexcept = 0;
            virtual int32_t __stdcall get_StrokeLineCap(int32_t*) noexcept = 0;
            virtual int32_t __stdcall get_StrokeLineJoin(int32_t*) noexcept = 0;
            virtual int32_t __stdcall get_FillRule(int32_t*) noexcept = 0;
            virtual int32_t __stdcall ClipPathGeometry(void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IRenderableView2>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_SvgRoot(void**) noexcept = 0;
            virtual int32_t __stdcall get_Fill(struct struct_Windows_UI_Color*) noexcept = 0;
            virtual int32_t __stdcall get_Stroke(struct struct_Windows_UI_Color*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IRenderableViewFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void*, void**, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IRenderableViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IRenderableViewManagerFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::ISvgView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_Device(void**) noexcept = 0;
            virtual int32_t __stdcall get_DeviceContext(void**) noexcept = 0;
            virtual int32_t __stdcall get_CanvasSize(winrt::Windows::Foundation::Size*) noexcept = 0;
            virtual int32_t __stdcall get_Templates(void**) noexcept = 0;
            virtual int32_t __stdcall get_Brushes(void**) noexcept = 0;
            virtual int32_t __stdcall Invalidate() noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::ISvgView2>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_Group(void**) noexcept = 0;
            virtual int32_t __stdcall put_Group(void*) noexcept = 0;
            virtual int32_t __stdcall get_CurrentColor(struct struct_Windows_UI_Color*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::ISvgViewFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::ISvgViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ISymbolView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_MinX(float*) noexcept = 0;
            virtual int32_t __stdcall get_MinY(float*) noexcept = 0;
            virtual int32_t __stdcall get_VbWidth(float*) noexcept = 0;
            virtual int32_t __stdcall get_VbHeight(float*) noexcept = 0;
            virtual int32_t __stdcall get_Align(void**) noexcept = 0;
            virtual int32_t __stdcall get_MeetOrSlice(int32_t*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::ISymbolView2>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ISymbolViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ITSpanView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_Rotate(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::ITSpanView2>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ITSpanViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ITextView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_X(void**) noexcept = 0;
            virtual int32_t __stdcall get_Y(void**) noexcept = 0;
            virtual int32_t __stdcall get_DX(void**) noexcept = 0;
            virtual int32_t __stdcall get_DY(void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::ITextView2>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ITextViewFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::ITextViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::ITextViewManagerFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IUnsupportedSvgViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IUnsupportedSvgViewManagerFactory>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(void*, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::RNSVG::IUseView>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::RNSVG::IUseViewManager>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_RNSVG_IBrushView
    {
        [[nodiscard]] auto Brush() const;
        auto CreateBrush() const;
        auto SetBounds(winrt::Windows::Foundation::Rect const& rect) const;
    };
    template <> struct consume<winrt::RNSVG::IBrushView>
    {
        template <typename D> using type = consume_RNSVG_IBrushView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IBrushView2
    {
    };
    template <> struct consume<winrt::RNSVG::IBrushView2>
    {
        template <typename D> using type = consume_RNSVG_IBrushView2<D>;
    };
    template <typename D>
    struct consume_RNSVG_IBrushViewFactory
    {
        auto CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const;
    };
    template <> struct consume<winrt::RNSVG::IBrushViewFactory>
    {
        template <typename D> using type = consume_RNSVG_IBrushViewFactory<D>;
    };
    template <typename D>
    struct consume_RNSVG_ICircleView
    {
    };
    template <> struct consume<winrt::RNSVG::ICircleView>
    {
        template <typename D> using type = consume_RNSVG_ICircleView<D>;
    };
    template <typename D>
    struct consume_RNSVG_ICircleViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::ICircleViewManager>
    {
        template <typename D> using type = consume_RNSVG_ICircleViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IClipPathView
    {
    };
    template <> struct consume<winrt::RNSVG::IClipPathView>
    {
        template <typename D> using type = consume_RNSVG_IClipPathView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IClipPathViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IClipPathViewManager>
    {
        template <typename D> using type = consume_RNSVG_IClipPathViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_ID2DBrush
    {
    };
    template <> struct consume<winrt::RNSVG::ID2DBrush>
    {
        template <typename D> using type = consume_RNSVG_ID2DBrush<D>;
    };
    template <typename D>
    struct consume_RNSVG_ID2DDevice
    {
    };
    template <> struct consume<winrt::RNSVG::ID2DDevice>
    {
        template <typename D> using type = consume_RNSVG_ID2DDevice<D>;
    };
    template <typename D>
    struct consume_RNSVG_ID2DDeviceContext
    {
    };
    template <> struct consume<winrt::RNSVG::ID2DDeviceContext>
    {
        template <typename D> using type = consume_RNSVG_ID2DDeviceContext<D>;
    };
    template <typename D>
    struct consume_RNSVG_ID2DGeometry
    {
    };
    template <> struct consume<winrt::RNSVG::ID2DGeometry>
    {
        template <typename D> using type = consume_RNSVG_ID2DGeometry<D>;
    };
    template <typename D>
    struct consume_RNSVG_IDefsView
    {
    };
    template <> struct consume<winrt::RNSVG::IDefsView>
    {
        template <typename D> using type = consume_RNSVG_IDefsView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IDefsViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IDefsViewManager>
    {
        template <typename D> using type = consume_RNSVG_IDefsViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IEllipseView
    {
    };
    template <> struct consume<winrt::RNSVG::IEllipseView>
    {
        template <typename D> using type = consume_RNSVG_IEllipseView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IEllipseViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IEllipseViewManager>
    {
        template <typename D> using type = consume_RNSVG_IEllipseViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IGroupView
    {
        [[nodiscard]] auto FontSize() const;
        auto FontSize(float value) const;
        [[nodiscard]] auto FontFamily() const;
        auto FontFamily(param::hstring const& value) const;
        [[nodiscard]] auto FontWeight() const;
        auto FontWeight(param::hstring const& value) const;
        auto DrawGroup(winrt::RNSVG::D2DDeviceContext const& deviceContext, winrt::Windows::Foundation::Size const& size) const;
    };
    template <> struct consume<winrt::RNSVG::IGroupView>
    {
        template <typename D> using type = consume_RNSVG_IGroupView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IGroupView2
    {
        [[nodiscard]] auto Children() const;
    };
    template <> struct consume<winrt::RNSVG::IGroupView2>
    {
        template <typename D> using type = consume_RNSVG_IGroupView2<D>;
    };
    template <typename D>
    struct consume_RNSVG_IGroupViewFactory
    {
        auto CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context, winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const;
    };
    template <> struct consume<winrt::RNSVG::IGroupViewFactory>
    {
        template <typename D> using type = consume_RNSVG_IGroupViewFactory<D>;
    };
    template <typename D>
    struct consume_RNSVG_IGroupViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IGroupViewManager>
    {
        template <typename D> using type = consume_RNSVG_IGroupViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IGroupViewManagerFactory
    {
        auto CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const;
    };
    template <> struct consume<winrt::RNSVG::IGroupViewManagerFactory>
    {
        template <typename D> using type = consume_RNSVG_IGroupViewManagerFactory<D>;
    };
    template <typename D>
    struct consume_RNSVG_IImageView
    {
    };
    template <> struct consume<winrt::RNSVG::IImageView>
    {
        template <typename D> using type = consume_RNSVG_IImageView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IImageViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IImageViewManager>
    {
        template <typename D> using type = consume_RNSVG_IImageViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_ILineView
    {
    };
    template <> struct consume<winrt::RNSVG::ILineView>
    {
        template <typename D> using type = consume_RNSVG_ILineView<D>;
    };
    template <typename D>
    struct consume_RNSVG_ILineViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::ILineViewManager>
    {
        template <typename D> using type = consume_RNSVG_ILineViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_ILinearGradientView
    {
    };
    template <> struct consume<winrt::RNSVG::ILinearGradientView>
    {
        template <typename D> using type = consume_RNSVG_ILinearGradientView<D>;
    };
    template <typename D>
    struct consume_RNSVG_ILinearGradientViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::ILinearGradientViewManager>
    {
        template <typename D> using type = consume_RNSVG_ILinearGradientViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IMarkerView
    {
    };
    template <> struct consume<winrt::RNSVG::IMarkerView>
    {
        template <typename D> using type = consume_RNSVG_IMarkerView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IMarkerViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IMarkerViewManager>
    {
        template <typename D> using type = consume_RNSVG_IMarkerViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IMaskView
    {
    };
    template <> struct consume<winrt::RNSVG::IMaskView>
    {
        template <typename D> using type = consume_RNSVG_IMaskView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IMaskViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IMaskViewManager>
    {
        template <typename D> using type = consume_RNSVG_IMaskViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IPathView
    {
    };
    template <> struct consume<winrt::RNSVG::IPathView>
    {
        template <typename D> using type = consume_RNSVG_IPathView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IPathViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IPathViewManager>
    {
        template <typename D> using type = consume_RNSVG_IPathViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IPatternView
    {
    };
    template <> struct consume<winrt::RNSVG::IPatternView>
    {
        template <typename D> using type = consume_RNSVG_IPatternView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IPatternViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IPatternViewManager>
    {
        template <typename D> using type = consume_RNSVG_IPatternViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRadialGradientView
    {
    };
    template <> struct consume<winrt::RNSVG::IRadialGradientView>
    {
        template <typename D> using type = consume_RNSVG_IRadialGradientView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRadialGradientViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IRadialGradientViewManager>
    {
        template <typename D> using type = consume_RNSVG_IRadialGradientViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IReactPackageProvider
    {
    };
    template <> struct consume<winrt::RNSVG::IReactPackageProvider>
    {
        template <typename D> using type = consume_RNSVG_IReactPackageProvider<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRectView
    {
    };
    template <> struct consume<winrt::RNSVG::IRectView>
    {
        template <typename D> using type = consume_RNSVG_IRectView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRectViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IRectViewManager>
    {
        template <typename D> using type = consume_RNSVG_IRectViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRenderable
    {
        [[nodiscard]] auto Geometry() const;
        auto Geometry(winrt::RNSVG::D2DGeometry const& value) const;
        [[nodiscard]] auto IsResponsible() const;
        auto IsResponsible(bool value) const;
        auto CreateResources() const;
        auto Draw(winrt::RNSVG::D2DDeviceContext const& deviceContext, winrt::Windows::Foundation::Size const& size) const;
        auto MergeProperties(winrt::RNSVG::IRenderable const& other) const;
        auto SaveDefinition() const;
        auto Unload() const;
        auto CreateGeometry(winrt::RNSVG::D2DDeviceContext const& deviceContext) const;
        auto HitTest(winrt::Windows::Foundation::Point const& point) const;
    };
    template <> struct consume<winrt::RNSVG::IRenderable>
    {
        template <typename D> using type = consume_RNSVG_IRenderable<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRenderablePaper
    {
        [[nodiscard]] auto SvgParent() const;
        auto SvgParent(winrt::Windows::UI::Xaml::FrameworkElement const& value) const;
        auto UpdateProperties(winrt::Microsoft::ReactNative::IJSValueReader const& reader, bool forceUpdate, bool invalidate) const;
    };
    template <> struct consume<winrt::RNSVG::IRenderablePaper>
    {
        template <typename D> using type = consume_RNSVG_IRenderablePaper<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRenderableView
    {
        [[nodiscard]] auto IsUnloaded() const;
        [[nodiscard]] auto Id() const;
        [[nodiscard]] auto SvgTransform() const;
        [[nodiscard]] auto FillOpacity() const;
        [[nodiscard]] auto FillBrushId() const;
        [[nodiscard]] auto StrokeOpacity() const;
        [[nodiscard]] auto StrokeBrushId() const;
        [[nodiscard]] auto StrokeWidth() const;
        [[nodiscard]] auto StrokeMiterLimit() const;
        [[nodiscard]] auto StrokeDashOffset() const;
        [[nodiscard]] auto StrokeDashArray() const;
        [[nodiscard]] auto StrokeLineCap() const;
        [[nodiscard]] auto StrokeLineJoin() const;
        [[nodiscard]] auto FillRule() const;
        auto ClipPathGeometry(winrt::RNSVG::D2DDeviceContext const& deviceContext) const;
    };
    template <> struct consume<winrt::RNSVG::IRenderableView>
    {
        template <typename D> using type = consume_RNSVG_IRenderableView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRenderableView2
    {
        [[nodiscard]] auto SvgRoot() const;
        [[nodiscard]] auto Fill() const;
        [[nodiscard]] auto Stroke() const;
    };
    template <> struct consume<winrt::RNSVG::IRenderableView2>
    {
        template <typename D> using type = consume_RNSVG_IRenderableView2<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRenderableViewFactory
    {
        auto CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context, winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const;
    };
    template <> struct consume<winrt::RNSVG::IRenderableViewFactory>
    {
        template <typename D> using type = consume_RNSVG_IRenderableViewFactory<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRenderableViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IRenderableViewManager>
    {
        template <typename D> using type = consume_RNSVG_IRenderableViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IRenderableViewManagerFactory
    {
        auto CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const;
    };
    template <> struct consume<winrt::RNSVG::IRenderableViewManagerFactory>
    {
        template <typename D> using type = consume_RNSVG_IRenderableViewManagerFactory<D>;
    };
    template <typename D>
    struct consume_RNSVG_ISvgView
    {
        [[nodiscard]] auto Device() const;
        [[nodiscard]] auto DeviceContext() const;
        [[nodiscard]] auto CanvasSize() const;
        [[nodiscard]] auto Templates() const;
        [[nodiscard]] auto Brushes() const;
        auto Invalidate() const;
    };
    template <> struct consume<winrt::RNSVG::ISvgView>
    {
        template <typename D> using type = consume_RNSVG_ISvgView<D>;
    };
    template <typename D>
    struct consume_RNSVG_ISvgView2
    {
        [[nodiscard]] auto Group() const;
        auto Group(winrt::RNSVG::GroupView const& value) const;
        [[nodiscard]] auto CurrentColor() const;
    };
    template <> struct consume<winrt::RNSVG::ISvgView2>
    {
        template <typename D> using type = consume_RNSVG_ISvgView2<D>;
    };
    template <typename D>
    struct consume_RNSVG_ISvgViewFactory
    {
        auto CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context) const;
    };
    template <> struct consume<winrt::RNSVG::ISvgViewFactory>
    {
        template <typename D> using type = consume_RNSVG_ISvgViewFactory<D>;
    };
    template <typename D>
    struct consume_RNSVG_ISvgViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::ISvgViewManager>
    {
        template <typename D> using type = consume_RNSVG_ISvgViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_ISymbolView
    {
        [[nodiscard]] auto MinX() const;
        [[nodiscard]] auto MinY() const;
        [[nodiscard]] auto VbWidth() const;
        [[nodiscard]] auto VbHeight() const;
        [[nodiscard]] auto Align() const;
        [[nodiscard]] auto MeetOrSlice() const;
    };
    template <> struct consume<winrt::RNSVG::ISymbolView>
    {
        template <typename D> using type = consume_RNSVG_ISymbolView<D>;
    };
    template <typename D>
    struct consume_RNSVG_ISymbolView2
    {
    };
    template <> struct consume<winrt::RNSVG::ISymbolView2>
    {
        template <typename D> using type = consume_RNSVG_ISymbolView2<D>;
    };
    template <typename D>
    struct consume_RNSVG_ISymbolViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::ISymbolViewManager>
    {
        template <typename D> using type = consume_RNSVG_ISymbolViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_ITSpanView
    {
        [[nodiscard]] auto Rotate() const;
    };
    template <> struct consume<winrt::RNSVG::ITSpanView>
    {
        template <typename D> using type = consume_RNSVG_ITSpanView<D>;
    };
    template <typename D>
    struct consume_RNSVG_ITSpanView2
    {
    };
    template <> struct consume<winrt::RNSVG::ITSpanView2>
    {
        template <typename D> using type = consume_RNSVG_ITSpanView2<D>;
    };
    template <typename D>
    struct consume_RNSVG_ITSpanViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::ITSpanViewManager>
    {
        template <typename D> using type = consume_RNSVG_ITSpanViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_ITextView
    {
        [[nodiscard]] auto X() const;
        [[nodiscard]] auto Y() const;
        [[nodiscard]] auto DX() const;
        [[nodiscard]] auto DY() const;
    };
    template <> struct consume<winrt::RNSVG::ITextView>
    {
        template <typename D> using type = consume_RNSVG_ITextView<D>;
    };
    template <typename D>
    struct consume_RNSVG_ITextView2
    {
    };
    template <> struct consume<winrt::RNSVG::ITextView2>
    {
        template <typename D> using type = consume_RNSVG_ITextView2<D>;
    };
    template <typename D>
    struct consume_RNSVG_ITextViewFactory
    {
        auto CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const;
    };
    template <> struct consume<winrt::RNSVG::ITextViewFactory>
    {
        template <typename D> using type = consume_RNSVG_ITextViewFactory<D>;
    };
    template <typename D>
    struct consume_RNSVG_ITextViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::ITextViewManager>
    {
        template <typename D> using type = consume_RNSVG_ITextViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_ITextViewManagerFactory
    {
        auto CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const;
    };
    template <> struct consume<winrt::RNSVG::ITextViewManagerFactory>
    {
        template <typename D> using type = consume_RNSVG_ITextViewManagerFactory<D>;
    };
    template <typename D>
    struct consume_RNSVG_IUnsupportedSvgViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IUnsupportedSvgViewManager>
    {
        template <typename D> using type = consume_RNSVG_IUnsupportedSvgViewManager<D>;
    };
    template <typename D>
    struct consume_RNSVG_IUnsupportedSvgViewManagerFactory
    {
        auto CreateInstance(param::hstring const& name) const;
    };
    template <> struct consume<winrt::RNSVG::IUnsupportedSvgViewManagerFactory>
    {
        template <typename D> using type = consume_RNSVG_IUnsupportedSvgViewManagerFactory<D>;
    };
    template <typename D>
    struct consume_RNSVG_IUseView
    {
    };
    template <> struct consume<winrt::RNSVG::IUseView>
    {
        template <typename D> using type = consume_RNSVG_IUseView<D>;
    };
    template <typename D>
    struct consume_RNSVG_IUseViewManager
    {
    };
    template <> struct consume<winrt::RNSVG::IUseViewManager>
    {
        template <typename D> using type = consume_RNSVG_IUseViewManager<D>;
    };
    struct struct_RNSVG_SVGLength
    {
        float Value;
        int32_t Unit;
    };
    template <> struct abi<RNSVG::SVGLength>
    {
        using type = struct_RNSVG_SVGLength;
    };
}
#endif
