// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_RNSVG_2_H
#define WINRT_RNSVG_2_H
#include "winrt/impl/Microsoft.ReactNative.2.h"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/RNSVG.1.h"
WINRT_EXPORT namespace winrt::RNSVG
{
    struct SVGLength
    {
        float Value;
        winrt::RNSVG::LengthType Unit;
    };
    inline bool operator==(SVGLength const& left, SVGLength const& right) noexcept
    {
        return left.Value == right.Value && left.Unit == right.Unit;
    }
    inline bool operator!=(SVGLength const& left, SVGLength const& right) noexcept
    {
        return !(left == right);
    }
    struct WINRT_IMPL_EMPTY_BASES BrushView : winrt::RNSVG::IBrushView2,
        impl::base<BrushView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<BrushView, winrt::RNSVG::IBrushView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        BrushView(std::nullptr_t) noexcept {}
        BrushView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IBrushView2(ptr, take_ownership_from_abi) {}
        BrushView();
    };
    struct WINRT_IMPL_EMPTY_BASES CircleView : winrt::RNSVG::ICircleView,
        impl::base<CircleView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<CircleView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        CircleView(std::nullptr_t) noexcept {}
        CircleView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ICircleView(ptr, take_ownership_from_abi) {}
        CircleView();
    };
    struct WINRT_IMPL_EMPTY_BASES CircleViewManager : winrt::RNSVG::ICircleViewManager,
        impl::base<CircleViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<CircleViewManager, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        CircleViewManager(std::nullptr_t) noexcept {}
        CircleViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ICircleViewManager(ptr, take_ownership_from_abi) {}
        CircleViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES ClipPathView : winrt::RNSVG::IClipPathView,
        impl::base<ClipPathView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<ClipPathView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        ClipPathView(std::nullptr_t) noexcept {}
        ClipPathView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IClipPathView(ptr, take_ownership_from_abi) {}
        ClipPathView();
    };
    struct WINRT_IMPL_EMPTY_BASES ClipPathViewManager : winrt::RNSVG::IClipPathViewManager,
        impl::base<ClipPathViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<ClipPathViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        ClipPathViewManager(std::nullptr_t) noexcept {}
        ClipPathViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IClipPathViewManager(ptr, take_ownership_from_abi) {}
        ClipPathViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES D2DBrush : winrt::RNSVG::ID2DBrush
    {
        D2DBrush(std::nullptr_t) noexcept {}
        D2DBrush(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ID2DBrush(ptr, take_ownership_from_abi) {}
        D2DBrush();
    };
    struct WINRT_IMPL_EMPTY_BASES D2DDevice : winrt::RNSVG::ID2DDevice
    {
        D2DDevice(std::nullptr_t) noexcept {}
        D2DDevice(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ID2DDevice(ptr, take_ownership_from_abi) {}
        D2DDevice();
    };
    struct WINRT_IMPL_EMPTY_BASES D2DDeviceContext : winrt::RNSVG::ID2DDeviceContext
    {
        D2DDeviceContext(std::nullptr_t) noexcept {}
        D2DDeviceContext(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ID2DDeviceContext(ptr, take_ownership_from_abi) {}
        D2DDeviceContext();
    };
    struct WINRT_IMPL_EMPTY_BASES D2DGeometry : winrt::RNSVG::ID2DGeometry
    {
        D2DGeometry(std::nullptr_t) noexcept {}
        D2DGeometry(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ID2DGeometry(ptr, take_ownership_from_abi) {}
        D2DGeometry();
    };
    struct WINRT_IMPL_EMPTY_BASES DefsView : winrt::RNSVG::IDefsView,
        impl::base<DefsView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<DefsView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        DefsView(std::nullptr_t) noexcept {}
        DefsView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IDefsView(ptr, take_ownership_from_abi) {}
        DefsView();
    };
    struct WINRT_IMPL_EMPTY_BASES DefsViewManager : winrt::RNSVG::IDefsViewManager,
        impl::base<DefsViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<DefsViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        DefsViewManager(std::nullptr_t) noexcept {}
        DefsViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IDefsViewManager(ptr, take_ownership_from_abi) {}
        DefsViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES EllipseView : winrt::RNSVG::IEllipseView,
        impl::base<EllipseView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<EllipseView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        EllipseView(std::nullptr_t) noexcept {}
        EllipseView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IEllipseView(ptr, take_ownership_from_abi) {}
        EllipseView();
    };
    struct WINRT_IMPL_EMPTY_BASES EllipseViewManager : winrt::RNSVG::IEllipseViewManager,
        impl::base<EllipseViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<EllipseViewManager, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        EllipseViewManager(std::nullptr_t) noexcept {}
        EllipseViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IEllipseViewManager(ptr, take_ownership_from_abi) {}
        EllipseViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES GroupView : winrt::RNSVG::IGroupView2,
        impl::base<GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<GroupView, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        GroupView(std::nullptr_t) noexcept {}
        GroupView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IGroupView2(ptr, take_ownership_from_abi) {}
        explicit GroupView(winrt::Microsoft::ReactNative::IReactContext const& context);
    };
    struct WINRT_IMPL_EMPTY_BASES GroupViewManager : winrt::RNSVG::IGroupViewManager,
        impl::base<GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<GroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        GroupViewManager(std::nullptr_t) noexcept {}
        GroupViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IGroupViewManager(ptr, take_ownership_from_abi) {}
        GroupViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES ImageView : winrt::RNSVG::IImageView,
        impl::base<ImageView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<ImageView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        ImageView(std::nullptr_t) noexcept {}
        ImageView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IImageView(ptr, take_ownership_from_abi) {}
        ImageView();
    };
    struct WINRT_IMPL_EMPTY_BASES ImageViewManager : winrt::RNSVG::IImageViewManager,
        impl::base<ImageViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<ImageViewManager, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        ImageViewManager(std::nullptr_t) noexcept {}
        ImageViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IImageViewManager(ptr, take_ownership_from_abi) {}
        ImageViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES LineView : winrt::RNSVG::ILineView,
        impl::base<LineView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<LineView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        LineView(std::nullptr_t) noexcept {}
        LineView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ILineView(ptr, take_ownership_from_abi) {}
        LineView();
    };
    struct WINRT_IMPL_EMPTY_BASES LineViewManager : winrt::RNSVG::ILineViewManager,
        impl::base<LineViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<LineViewManager, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        LineViewManager(std::nullptr_t) noexcept {}
        LineViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ILineViewManager(ptr, take_ownership_from_abi) {}
        LineViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES LinearGradientView : winrt::RNSVG::ILinearGradientView,
        impl::base<LinearGradientView, winrt::RNSVG::BrushView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<LinearGradientView, winrt::RNSVG::IBrushView2, winrt::RNSVG::IBrushView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        LinearGradientView(std::nullptr_t) noexcept {}
        LinearGradientView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ILinearGradientView(ptr, take_ownership_from_abi) {}
        LinearGradientView();
    };
    struct WINRT_IMPL_EMPTY_BASES LinearGradientViewManager : winrt::RNSVG::ILinearGradientViewManager,
        impl::base<LinearGradientViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<LinearGradientViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        LinearGradientViewManager(std::nullptr_t) noexcept {}
        LinearGradientViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ILinearGradientViewManager(ptr, take_ownership_from_abi) {}
        LinearGradientViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES MarkerView : winrt::RNSVG::IMarkerView,
        impl::base<MarkerView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<MarkerView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        MarkerView(std::nullptr_t) noexcept {}
        MarkerView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IMarkerView(ptr, take_ownership_from_abi) {}
        MarkerView();
    };
    struct WINRT_IMPL_EMPTY_BASES MarkerViewManager : winrt::RNSVG::IMarkerViewManager,
        impl::base<MarkerViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<MarkerViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        MarkerViewManager(std::nullptr_t) noexcept {}
        MarkerViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IMarkerViewManager(ptr, take_ownership_from_abi) {}
        MarkerViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES MaskView : winrt::RNSVG::IMaskView,
        impl::base<MaskView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<MaskView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        MaskView(std::nullptr_t) noexcept {}
        MaskView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IMaskView(ptr, take_ownership_from_abi) {}
        MaskView();
    };
    struct WINRT_IMPL_EMPTY_BASES MaskViewManager : winrt::RNSVG::IMaskViewManager,
        impl::base<MaskViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<MaskViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        MaskViewManager(std::nullptr_t) noexcept {}
        MaskViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IMaskViewManager(ptr, take_ownership_from_abi) {}
        MaskViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES PathView : winrt::RNSVG::IPathView,
        impl::base<PathView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<PathView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        PathView(std::nullptr_t) noexcept {}
        PathView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IPathView(ptr, take_ownership_from_abi) {}
        PathView();
    };
    struct WINRT_IMPL_EMPTY_BASES PathViewManager : winrt::RNSVG::IPathViewManager,
        impl::base<PathViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<PathViewManager, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        PathViewManager(std::nullptr_t) noexcept {}
        PathViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IPathViewManager(ptr, take_ownership_from_abi) {}
        PathViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES PatternView : winrt::RNSVG::IPatternView,
        impl::base<PatternView, winrt::RNSVG::BrushView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<PatternView, winrt::RNSVG::IBrushView2, winrt::RNSVG::IBrushView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        PatternView(std::nullptr_t) noexcept {}
        PatternView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IPatternView(ptr, take_ownership_from_abi) {}
        PatternView();
    };
    struct WINRT_IMPL_EMPTY_BASES PatternViewManager : winrt::RNSVG::IPatternViewManager,
        impl::base<PatternViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<PatternViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        PatternViewManager(std::nullptr_t) noexcept {}
        PatternViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IPatternViewManager(ptr, take_ownership_from_abi) {}
        PatternViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES RadialGradientView : winrt::RNSVG::IRadialGradientView,
        impl::base<RadialGradientView, winrt::RNSVG::BrushView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<RadialGradientView, winrt::RNSVG::IBrushView2, winrt::RNSVG::IBrushView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        RadialGradientView(std::nullptr_t) noexcept {}
        RadialGradientView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IRadialGradientView(ptr, take_ownership_from_abi) {}
        RadialGradientView();
    };
    struct WINRT_IMPL_EMPTY_BASES RadialGradientViewManager : winrt::RNSVG::IRadialGradientViewManager,
        impl::base<RadialGradientViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<RadialGradientViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        RadialGradientViewManager(std::nullptr_t) noexcept {}
        RadialGradientViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IRadialGradientViewManager(ptr, take_ownership_from_abi) {}
        RadialGradientViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES ReactPackageProvider : winrt::RNSVG::IReactPackageProvider,
        impl::require<ReactPackageProvider, winrt::Microsoft::ReactNative::IReactPackageProvider>
    {
        ReactPackageProvider(std::nullptr_t) noexcept {}
        ReactPackageProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IReactPackageProvider(ptr, take_ownership_from_abi) {}
        ReactPackageProvider();
    };
    struct WINRT_IMPL_EMPTY_BASES RectView : winrt::RNSVG::IRectView,
        impl::base<RectView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<RectView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        RectView(std::nullptr_t) noexcept {}
        RectView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IRectView(ptr, take_ownership_from_abi) {}
        RectView();
    };
    struct WINRT_IMPL_EMPTY_BASES RectViewManager : winrt::RNSVG::IRectViewManager,
        impl::base<RectViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<RectViewManager, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        RectViewManager(std::nullptr_t) noexcept {}
        RectViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IRectViewManager(ptr, take_ownership_from_abi) {}
        RectViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES RenderableView : winrt::RNSVG::IRenderableView2,
        impl::base<RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<RenderableView, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        RenderableView(std::nullptr_t) noexcept {}
        RenderableView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IRenderableView2(ptr, take_ownership_from_abi) {}
        explicit RenderableView(winrt::Microsoft::ReactNative::IReactContext const& context);
    };
    struct WINRT_IMPL_EMPTY_BASES RenderableViewManager : winrt::RNSVG::IRenderableViewManager,
        impl::require<RenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        RenderableViewManager(std::nullptr_t) noexcept {}
        RenderableViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IRenderableViewManager(ptr, take_ownership_from_abi) {}
        RenderableViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES SvgView : winrt::RNSVG::ISvgView2,
        impl::base<SvgView, winrt::Windows::UI::Xaml::Controls::Panel, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<SvgView, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::ISvgView, winrt::Windows::UI::Xaml::Controls::IPanel, winrt::Windows::UI::Xaml::Controls::IPanel2, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        SvgView(std::nullptr_t) noexcept {}
        SvgView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ISvgView2(ptr, take_ownership_from_abi) {}
        explicit SvgView(winrt::Microsoft::ReactNative::IReactContext const& context);
    };
    struct WINRT_IMPL_EMPTY_BASES SvgViewManager : winrt::RNSVG::ISvgViewManager,
        impl::require<SvgViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::Microsoft::ReactNative::IViewManagerWithPointerEvents>
    {
        SvgViewManager(std::nullptr_t) noexcept {}
        SvgViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ISvgViewManager(ptr, take_ownership_from_abi) {}
        SvgViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES SymbolView : winrt::RNSVG::ISymbolView2,
        impl::base<SymbolView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<SymbolView, winrt::RNSVG::ISymbolView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        SymbolView(std::nullptr_t) noexcept {}
        SymbolView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ISymbolView2(ptr, take_ownership_from_abi) {}
        SymbolView();
    };
    struct WINRT_IMPL_EMPTY_BASES SymbolViewManager : winrt::RNSVG::ISymbolViewManager,
        impl::base<SymbolViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<SymbolViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        SymbolViewManager(std::nullptr_t) noexcept {}
        SymbolViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ISymbolViewManager(ptr, take_ownership_from_abi) {}
        SymbolViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES TSpanView : winrt::RNSVG::ITSpanView2,
        impl::base<TSpanView, winrt::RNSVG::TextView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<TSpanView, winrt::RNSVG::ITSpanView, winrt::RNSVG::ITextView2, winrt::RNSVG::ITextView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        TSpanView(std::nullptr_t) noexcept {}
        TSpanView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ITSpanView2(ptr, take_ownership_from_abi) {}
        TSpanView();
    };
    struct WINRT_IMPL_EMPTY_BASES TSpanViewManager : winrt::RNSVG::ITSpanViewManager,
        impl::base<TSpanViewManager, winrt::RNSVG::TextViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<TSpanViewManager, winrt::RNSVG::ITextViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        TSpanViewManager(std::nullptr_t) noexcept {}
        TSpanViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ITSpanViewManager(ptr, take_ownership_from_abi) {}
        TSpanViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES TextView : winrt::RNSVG::ITextView2,
        impl::base<TextView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<TextView, winrt::RNSVG::ITextView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        TextView(std::nullptr_t) noexcept {}
        TextView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ITextView2(ptr, take_ownership_from_abi) {}
        TextView();
    };
    struct WINRT_IMPL_EMPTY_BASES TextViewManager : winrt::RNSVG::ITextViewManager,
        impl::base<TextViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<TextViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        TextViewManager(std::nullptr_t) noexcept {}
        TextViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::ITextViewManager(ptr, take_ownership_from_abi) {}
        TextViewManager();
    };
    struct WINRT_IMPL_EMPTY_BASES UnsupportedSvgViewManager : winrt::RNSVG::IUnsupportedSvgViewManager,
        impl::require<UnsupportedSvgViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithChildren>
    {
        UnsupportedSvgViewManager(std::nullptr_t) noexcept {}
        UnsupportedSvgViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IUnsupportedSvgViewManager(ptr, take_ownership_from_abi) {}
        explicit UnsupportedSvgViewManager(param::hstring const& name);
    };
    struct WINRT_IMPL_EMPTY_BASES UseView : winrt::RNSVG::IUseView,
        impl::base<UseView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        impl::require<UseView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>
    {
        UseView(std::nullptr_t) noexcept {}
        UseView(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IUseView(ptr, take_ownership_from_abi) {}
        UseView();
    };
    struct WINRT_IMPL_EMPTY_BASES UseViewManager : winrt::RNSVG::IUseViewManager,
        impl::base<UseViewManager, winrt::RNSVG::RenderableViewManager>,
        impl::require<UseViewManager, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>
    {
        UseViewManager(std::nullptr_t) noexcept {}
        UseViewManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::RNSVG::IUseViewManager(ptr, take_ownership_from_abi) {}
        UseViewManager();
    };
}
#endif
