// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_SQLitePlugin_0_H
#define WINRT_SQLitePlugin_0_H
WINRT_EXPORT namespace winrt::SQLitePlugin
{
    struct IReactPackageProvider;
    struct ReactPackageProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::SQLitePlugin::IReactPackageProvider>{ using type = interface_category; };
    template <> struct category<winrt::SQLitePlugin::ReactPackageProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::SQLitePlugin::ReactPackageProvider> = L"SQLitePlugin.ReactPackageProvider";
    template <> inline constexpr auto& name_v<winrt::SQLitePlugin::IReactPackageProvider> = L"SQLitePlugin.IReactPackageProvider";
    template <> inline constexpr guid guid_v<winrt::SQLitePlugin::IReactPackageProvider>{ 0x72CEC307,0x6636,0x5B26,{ 0x93,0xE5,0x11,0xE7,0x8D,0xB8,0xF7,0x9D } }; // 72CEC307-6636-5B26-93E5-11E78DB8F79D
    template <> struct default_interface<winrt::SQLitePlugin::ReactPackageProvider>{ using type = winrt::SQLitePlugin::IReactPackageProvider; };
    template <> struct abi<winrt::SQLitePlugin::IReactPackageProvider>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_SQLitePlugin_IReactPackageProvider
    {
    };
    template <> struct consume<winrt::SQLitePlugin::IReactPackageProvider>
    {
        template <typename D> using type = consume_SQLitePlugin_IReactPackageProvider<D>;
    };
}
#endif
