// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_BVLinearGradient_H
#define WINRT_BVLinearGradient_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.230706.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.230706.1"
#include "winrt/impl/Microsoft.ReactNative.2.h"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/BVLinearGradient.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_BVLinearGradient_IBVLinearGradientModule<D>::UpdateProperties(winrt::Microsoft::ReactNative::IJSValueReader const& reader) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::BVLinearGradient::IBVLinearGradientModule)->UpdateProperties(*(void**)(&reader)));
    }
    template <typename D> auto consume_BVLinearGradient_IBVLinearGradientModule<D>::DispatchCommand(param::hstring const& commandId, winrt::Microsoft::ReactNative::IJSValueReader const& commandArgsReader) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::BVLinearGradient::IBVLinearGradientModule)->DispatchCommand(*(void**)(&commandId), *(void**)(&commandArgsReader)));
    }
    template <typename D> auto consume_BVLinearGradient_IBVLinearGradientModuleFactory<D>::CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::BVLinearGradient::IBVLinearGradientModuleFactory)->CreateInstance(*(void**)(&context), &value));
        return winrt::BVLinearGradient::BVLinearGradientModule{ value, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::BVLinearGradient::IBVLinearGradientModule> : produce_base<D, winrt::BVLinearGradient::IBVLinearGradientModule>
    {
        int32_t __stdcall UpdateProperties(void* reader) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().UpdateProperties(*reinterpret_cast<winrt::Microsoft::ReactNative::IJSValueReader const*>(&reader));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall DispatchCommand(void* commandId, void* commandArgsReader) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().DispatchCommand(*reinterpret_cast<hstring const*>(&commandId), *reinterpret_cast<winrt::Microsoft::ReactNative::IJSValueReader const*>(&commandArgsReader));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::BVLinearGradient::IBVLinearGradientModuleFactory> : produce_base<D, winrt::BVLinearGradient::IBVLinearGradientModuleFactory>
    {
        int32_t __stdcall CreateInstance(void* context, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::BVLinearGradient::BVLinearGradientModule>(this->shim().CreateInstance(*reinterpret_cast<winrt::Microsoft::ReactNative::IReactContext const*>(&context)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::BVLinearGradient::IReactPackageProvider> : produce_base<D, winrt::BVLinearGradient::IReactPackageProvider>
    {
    };
#endif
}
WINRT_EXPORT namespace winrt::BVLinearGradient
{
    inline BVLinearGradientModule::BVLinearGradientModule(winrt::Microsoft::ReactNative::IReactContext const& context) :
        BVLinearGradientModule(impl::call_factory<BVLinearGradientModule, IBVLinearGradientModuleFactory>([&](IBVLinearGradientModuleFactory const& f) { return f.CreateInstance(context); }))
    {
    }
    inline ReactPackageProvider::ReactPackageProvider() :
        ReactPackageProvider(impl::call_factory_cast<ReactPackageProvider(*)(winrt::Windows::Foundation::IActivationFactory const&), ReactPackageProvider>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<ReactPackageProvider>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::BVLinearGradient::IBVLinearGradientModule> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BVLinearGradient::IBVLinearGradientModuleFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BVLinearGradient::IReactPackageProvider> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BVLinearGradient::BVLinearGradientModule> : winrt::impl::hash_base {};
    template<> struct hash<winrt::BVLinearGradient::ReactPackageProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
