// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_ReactNativeShare_H
#define WINRT_ReactNativeShare_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.230706.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.230706.1"
#include "winrt/impl/Microsoft.ReactNative.2.h"
#include "winrt/impl/ReactNativeShare.2.h"
namespace winrt::impl
{
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::ReactNativeShare::IReactPackageProvider> : produce_base<D, winrt::ReactNativeShare::IReactPackageProvider>
    {
    };
#endif
}
WINRT_EXPORT namespace winrt::ReactNativeShare
{
    inline ReactPackageProvider::ReactPackageProvider() :
        ReactPackageProvider(impl::call_factory_cast<ReactPackageProvider(*)(winrt::Windows::Foundation::IActivationFactory const&), ReactPackageProvider>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<ReactPackageProvider>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::ReactNativeShare::IReactPackageProvider> : winrt::impl::hash_base {};
    template<> struct hash<winrt::ReactNativeShare::ReactPackageProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
