// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_RNScreens_H
#define WINRT_RNScreens_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.230706.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.230706.1"
#include "winrt/impl/Microsoft.ReactNative.2.h"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/RNScreens.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_RNScreens_IRNScreensModule<D>::UpdateProperties(winrt::Microsoft::ReactNative::IJSValueReader const& reader) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNScreens::IRNScreensModule)->UpdateProperties(*(void**)(&reader)));
    }
    template <typename D> auto consume_RNScreens_IRNScreensModule<D>::DispatchCommand(param::hstring const& commandId, winrt::Microsoft::ReactNative::IJSValueReader const& commandArgsReader) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNScreens::IRNScreensModule)->DispatchCommand(*(void**)(&commandId), *(void**)(&commandArgsReader)));
    }
    template <typename D> auto consume_RNScreens_IRNScreensModuleFactory<D>::CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNScreens::IRNScreensModuleFactory)->CreateInstance(*(void**)(&context), &value));
        return winrt::RNScreens::RNScreensModule{ value, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNScreens::IRNScreensModule> : produce_base<D, winrt::RNScreens::IRNScreensModule>
    {
        int32_t __stdcall UpdateProperties(void* reader) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().UpdateProperties(*reinterpret_cast<winrt::Microsoft::ReactNative::IJSValueReader const*>(&reader));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall DispatchCommand(void* commandId, void* commandArgsReader) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().DispatchCommand(*reinterpret_cast<hstring const*>(&commandId), *reinterpret_cast<winrt::Microsoft::ReactNative::IJSValueReader const*>(&commandArgsReader));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNScreens::IRNScreensModuleFactory> : produce_base<D, winrt::RNScreens::IRNScreensModuleFactory>
    {
        int32_t __stdcall CreateInstance(void* context, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNScreens::RNScreensModule>(this->shim().CreateInstance(*reinterpret_cast<winrt::Microsoft::ReactNative::IReactContext const*>(&context)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNScreens::IReactPackageProvider> : produce_base<D, winrt::RNScreens::IReactPackageProvider>
    {
    };
#endif
}
WINRT_EXPORT namespace winrt::RNScreens
{
    inline RNScreensModule::RNScreensModule(winrt::Microsoft::ReactNative::IReactContext const& context) :
        RNScreensModule(impl::call_factory<RNScreensModule, IRNScreensModuleFactory>([&](IRNScreensModuleFactory const& f) { return f.CreateInstance(context); }))
    {
    }
    inline ReactPackageProvider::ReactPackageProvider() :
        ReactPackageProvider(impl::call_factory_cast<ReactPackageProvider(*)(winrt::Windows::Foundation::IActivationFactory const&), ReactPackageProvider>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<ReactPackageProvider>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::RNScreens::IRNScreensModule> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNScreens::IRNScreensModuleFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNScreens::IReactPackageProvider> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNScreens::RNScreensModule> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNScreens::ReactPackageProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
