// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_RNSVG_H
#define WINRT_RNSVG_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.230706.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.230706.1"
#include "winrt/impl/Microsoft.ReactNative.2.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.Foundation.Numerics.2.h"
#include "winrt/impl/Windows.UI.2.h"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/RNSVG.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_RNSVG_IBrushView<D>::Brush() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IBrushView)->get_Brush(&value));
        return winrt::RNSVG::D2DBrush{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IBrushView<D>::CreateBrush() const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IBrushView)->CreateBrush());
    }
    template <typename D> auto consume_RNSVG_IBrushView<D>::SetBounds(winrt::Windows::Foundation::Rect const& rect) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IBrushView)->SetBounds(impl::bind_in(rect)));
    }
    template <typename D> auto consume_RNSVG_IBrushViewFactory<D>::CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IBrushViewFactory)->CreateInstance(*(void**)(&baseInterface), impl::bind_out(innerInterface), &value));
        return winrt::RNSVG::BrushView{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IGroupView<D>::FontSize() const
    {
        float value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupView)->get_FontSize(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_IGroupView<D>::FontSize(float value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupView)->put_FontSize(value));
    }
    template <typename D> auto consume_RNSVG_IGroupView<D>::FontFamily() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupView)->get_FontFamily(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IGroupView<D>::FontFamily(param::hstring const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupView)->put_FontFamily(*(void**)(&value)));
    }
    template <typename D> auto consume_RNSVG_IGroupView<D>::FontWeight() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupView)->get_FontWeight(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IGroupView<D>::FontWeight(param::hstring const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupView)->put_FontWeight(*(void**)(&value)));
    }
    template <typename D> auto consume_RNSVG_IGroupView<D>::DrawGroup(winrt::RNSVG::D2DDeviceContext const& deviceContext, winrt::Windows::Foundation::Size const& size) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupView)->DrawGroup(*(void**)(&deviceContext), impl::bind_in(size)));
    }
    template <typename D> auto consume_RNSVG_IGroupView2<D>::Children() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupView2)->get_Children(&value));
        return winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::IRenderable>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IGroupViewFactory<D>::CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context, winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupViewFactory)->CreateInstance(*(void**)(&context), *(void**)(&baseInterface), impl::bind_out(innerInterface), &value));
        return winrt::RNSVG::GroupView{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IGroupViewManagerFactory<D>::CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IGroupViewManagerFactory)->CreateInstance(*(void**)(&baseInterface), impl::bind_out(innerInterface), &value));
        return winrt::RNSVG::GroupViewManager{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::Geometry() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->get_Geometry(&value));
        return winrt::RNSVG::D2DGeometry{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::Geometry(winrt::RNSVG::D2DGeometry const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->put_Geometry(*(void**)(&value)));
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::IsResponsible() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->get_IsResponsible(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::IsResponsible(bool value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->put_IsResponsible(value));
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::CreateResources() const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->CreateResources());
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::Draw(winrt::RNSVG::D2DDeviceContext const& deviceContext, winrt::Windows::Foundation::Size const& size) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->Draw(*(void**)(&deviceContext), impl::bind_in(size)));
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::MergeProperties(winrt::RNSVG::IRenderable const& other) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->MergeProperties(*(void**)(&other)));
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::SaveDefinition() const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->SaveDefinition());
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::Unload() const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->Unload());
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::CreateGeometry(winrt::RNSVG::D2DDeviceContext const& deviceContext) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->CreateGeometry(*(void**)(&deviceContext)));
    }
    template <typename D> auto consume_RNSVG_IRenderable<D>::HitTest(winrt::Windows::Foundation::Point const& point) const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderable)->HitTest(impl::bind_in(point), &result));
        return winrt::RNSVG::IRenderable{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderablePaper<D>::SvgParent() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderablePaper)->get_SvgParent(&value));
        return winrt::Windows::UI::Xaml::FrameworkElement{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderablePaper<D>::SvgParent(winrt::Windows::UI::Xaml::FrameworkElement const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderablePaper)->put_SvgParent(*(void**)(&value)));
    }
    template <typename D> auto consume_RNSVG_IRenderablePaper<D>::UpdateProperties(winrt::Microsoft::ReactNative::IJSValueReader const& reader, bool forceUpdate, bool invalidate) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderablePaper)->UpdateProperties(*(void**)(&reader), forceUpdate, invalidate));
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::IsUnloaded() const
    {
        bool value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_IsUnloaded(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::Id() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_Id(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::SvgTransform() const
    {
        winrt::Windows::Foundation::Numerics::float3x2 value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_SvgTransform(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::FillOpacity() const
    {
        float value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_FillOpacity(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::FillBrushId() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_FillBrushId(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::StrokeOpacity() const
    {
        float value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_StrokeOpacity(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::StrokeBrushId() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_StrokeBrushId(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::StrokeWidth() const
    {
        winrt::RNSVG::SVGLength value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_StrokeWidth(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::StrokeMiterLimit() const
    {
        float value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_StrokeMiterLimit(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::StrokeDashOffset() const
    {
        float value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_StrokeDashOffset(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::StrokeDashArray() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_StrokeDashArray(&value));
        return winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::StrokeLineCap() const
    {
        winrt::RNSVG::LineCap value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_StrokeLineCap(reinterpret_cast<int32_t*>(&value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::StrokeLineJoin() const
    {
        winrt::RNSVG::LineJoin value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_StrokeLineJoin(reinterpret_cast<int32_t*>(&value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::FillRule() const
    {
        winrt::RNSVG::FillRule value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->get_FillRule(reinterpret_cast<int32_t*>(&value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView<D>::ClipPathGeometry(winrt::RNSVG::D2DDeviceContext const& deviceContext) const
    {
        void* result{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView)->ClipPathGeometry(*(void**)(&deviceContext), &result));
        return winrt::RNSVG::D2DGeometry{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderableView2<D>::SvgRoot() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView2)->get_SvgRoot(&value));
        return winrt::RNSVG::SvgView{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderableView2<D>::Fill() const
    {
        winrt::Windows::UI::Color value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView2)->get_Fill(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableView2<D>::Stroke() const
    {
        winrt::Windows::UI::Color value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableView2)->get_Stroke(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_IRenderableViewFactory<D>::CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context, winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableViewFactory)->CreateInstance(*(void**)(&context), *(void**)(&baseInterface), impl::bind_out(innerInterface), &value));
        return winrt::RNSVG::RenderableView{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IRenderableViewManagerFactory<D>::CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IRenderableViewManagerFactory)->CreateInstance(*(void**)(&baseInterface), impl::bind_out(innerInterface), &value));
        return winrt::RNSVG::RenderableViewManager{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ISvgView<D>::Device() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgView)->get_Device(&value));
        return winrt::RNSVG::D2DDevice{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ISvgView<D>::DeviceContext() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgView)->get_DeviceContext(&value));
        return winrt::RNSVG::D2DDeviceContext{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ISvgView<D>::CanvasSize() const
    {
        winrt::Windows::Foundation::Size value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgView)->get_CanvasSize(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_ISvgView<D>::Templates() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgView)->get_Templates(&value));
        return winrt::Windows::Foundation::Collections::IMap<hstring, winrt::RNSVG::IRenderable>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ISvgView<D>::Brushes() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgView)->get_Brushes(&value));
        return winrt::Windows::Foundation::Collections::IMap<hstring, winrt::RNSVG::IBrushView>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ISvgView<D>::Invalidate() const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgView)->Invalidate());
    }
    template <typename D> auto consume_RNSVG_ISvgView2<D>::Group() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgView2)->get_Group(&value));
        return winrt::RNSVG::GroupView{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ISvgView2<D>::Group(winrt::RNSVG::GroupView const& value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgView2)->put_Group(*(void**)(&value)));
    }
    template <typename D> auto consume_RNSVG_ISvgView2<D>::CurrentColor() const
    {
        winrt::Windows::UI::Color value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgView2)->get_CurrentColor(put_abi(value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_ISvgViewFactory<D>::CreateInstance(winrt::Microsoft::ReactNative::IReactContext const& context) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISvgViewFactory)->CreateInstance(*(void**)(&context), &value));
        return winrt::RNSVG::SvgView{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ISymbolView<D>::MinX() const
    {
        float value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISymbolView)->get_MinX(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_ISymbolView<D>::MinY() const
    {
        float value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISymbolView)->get_MinY(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_ISymbolView<D>::VbWidth() const
    {
        float value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISymbolView)->get_VbWidth(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_ISymbolView<D>::VbHeight() const
    {
        float value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISymbolView)->get_VbHeight(&value));
        return value;
    }
    template <typename D> auto consume_RNSVG_ISymbolView<D>::Align() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISymbolView)->get_Align(&value));
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ISymbolView<D>::MeetOrSlice() const
    {
        winrt::RNSVG::MeetOrSlice value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ISymbolView)->get_MeetOrSlice(reinterpret_cast<int32_t*>(&value)));
        return value;
    }
    template <typename D> auto consume_RNSVG_ITSpanView<D>::Rotate() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ITSpanView)->get_Rotate(&value));
        return winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ITextView<D>::X() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ITextView)->get_X(&value));
        return winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ITextView<D>::Y() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ITextView)->get_Y(&value));
        return winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ITextView<D>::DX() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ITextView)->get_DX(&value));
        return winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ITextView<D>::DY() const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ITextView)->get_DY(&value));
        return winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ITextViewFactory<D>::CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ITextViewFactory)->CreateInstance(*(void**)(&baseInterface), impl::bind_out(innerInterface), &value));
        return winrt::RNSVG::TextView{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_ITextViewManagerFactory<D>::CreateInstance(winrt::Windows::Foundation::IInspectable const& baseInterface, winrt::Windows::Foundation::IInspectable& innerInterface) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::ITextViewManagerFactory)->CreateInstance(*(void**)(&baseInterface), impl::bind_out(innerInterface), &value));
        return winrt::RNSVG::TextViewManager{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_RNSVG_IUnsupportedSvgViewManagerFactory<D>::CreateInstance(param::hstring const& name) const
    {
        void* value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::RNSVG::IUnsupportedSvgViewManagerFactory)->CreateInstance(*(void**)(&name), &value));
        return winrt::RNSVG::UnsupportedSvgViewManager{ value, take_ownership_from_abi };
    }
    template <typename D>
    struct produce<D, winrt::RNSVG::IBrushView> : produce_base<D, winrt::RNSVG::IBrushView>
    {
        int32_t __stdcall get_Brush(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::D2DBrush>(this->shim().Brush());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall CreateBrush() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CreateBrush();
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall SetBounds(winrt::Windows::Foundation::Rect rect) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetBounds(*reinterpret_cast<winrt::Windows::Foundation::Rect const*>(&rect));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IBrushView2> : produce_base<D, winrt::RNSVG::IBrushView2>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IBrushViewFactory> : produce_base<D, winrt::RNSVG::IBrushViewFactory>
    {
        int32_t __stdcall CreateInstance(void* baseInterface, void** innerInterface, void** value) noexcept final try
        {
            if (innerInterface) *innerInterface = nullptr;
            winrt::Windows::Foundation::IInspectable winrt_impl_innerInterface;
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::BrushView>(this->shim().CreateInstance(*reinterpret_cast<winrt::Windows::Foundation::IInspectable const*>(&baseInterface), winrt_impl_innerInterface));
                if (innerInterface) *innerInterface = detach_abi(winrt_impl_innerInterface);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ICircleView> : produce_base<D, winrt::RNSVG::ICircleView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ICircleViewManager> : produce_base<D, winrt::RNSVG::ICircleViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IClipPathView> : produce_base<D, winrt::RNSVG::IClipPathView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IClipPathViewManager> : produce_base<D, winrt::RNSVG::IClipPathViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ID2DBrush> : produce_base<D, winrt::RNSVG::ID2DBrush>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ID2DDevice> : produce_base<D, winrt::RNSVG::ID2DDevice>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ID2DDeviceContext> : produce_base<D, winrt::RNSVG::ID2DDeviceContext>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ID2DGeometry> : produce_base<D, winrt::RNSVG::ID2DGeometry>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IDefsView> : produce_base<D, winrt::RNSVG::IDefsView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IDefsViewManager> : produce_base<D, winrt::RNSVG::IDefsViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IEllipseView> : produce_base<D, winrt::RNSVG::IEllipseView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IEllipseViewManager> : produce_base<D, winrt::RNSVG::IEllipseViewManager>
    {
    };
#endif
    template <typename D>
    struct produce<D, winrt::RNSVG::IGroupView> : produce_base<D, winrt::RNSVG::IGroupView>
    {
        int32_t __stdcall get_FontSize(float* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<float>(this->shim().FontSize());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_FontSize(float value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().FontSize(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_FontFamily(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().FontFamily());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_FontFamily(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().FontFamily(*reinterpret_cast<hstring const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_FontWeight(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().FontWeight());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_FontWeight(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().FontWeight(*reinterpret_cast<hstring const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall DrawGroup(void* deviceContext, winrt::Windows::Foundation::Size size) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().DrawGroup(*reinterpret_cast<winrt::RNSVG::D2DDeviceContext const*>(&deviceContext), *reinterpret_cast<winrt::Windows::Foundation::Size const*>(&size));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IGroupView2> : produce_base<D, winrt::RNSVG::IGroupView2>
    {
        int32_t __stdcall get_Children(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::IRenderable>>(this->shim().Children());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IGroupViewFactory> : produce_base<D, winrt::RNSVG::IGroupViewFactory>
    {
        int32_t __stdcall CreateInstance(void* context, void* baseInterface, void** innerInterface, void** value) noexcept final try
        {
            if (innerInterface) *innerInterface = nullptr;
            winrt::Windows::Foundation::IInspectable winrt_impl_innerInterface;
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::GroupView>(this->shim().CreateInstance(*reinterpret_cast<winrt::Microsoft::ReactNative::IReactContext const*>(&context), *reinterpret_cast<winrt::Windows::Foundation::IInspectable const*>(&baseInterface), winrt_impl_innerInterface));
                if (innerInterface) *innerInterface = detach_abi(winrt_impl_innerInterface);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IGroupViewManager> : produce_base<D, winrt::RNSVG::IGroupViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IGroupViewManagerFactory> : produce_base<D, winrt::RNSVG::IGroupViewManagerFactory>
    {
        int32_t __stdcall CreateInstance(void* baseInterface, void** innerInterface, void** value) noexcept final try
        {
            if (innerInterface) *innerInterface = nullptr;
            winrt::Windows::Foundation::IInspectable winrt_impl_innerInterface;
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::GroupViewManager>(this->shim().CreateInstance(*reinterpret_cast<winrt::Windows::Foundation::IInspectable const*>(&baseInterface), winrt_impl_innerInterface));
                if (innerInterface) *innerInterface = detach_abi(winrt_impl_innerInterface);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IImageView> : produce_base<D, winrt::RNSVG::IImageView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IImageViewManager> : produce_base<D, winrt::RNSVG::IImageViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ILineView> : produce_base<D, winrt::RNSVG::ILineView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ILineViewManager> : produce_base<D, winrt::RNSVG::ILineViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ILinearGradientView> : produce_base<D, winrt::RNSVG::ILinearGradientView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ILinearGradientViewManager> : produce_base<D, winrt::RNSVG::ILinearGradientViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IMarkerView> : produce_base<D, winrt::RNSVG::IMarkerView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IMarkerViewManager> : produce_base<D, winrt::RNSVG::IMarkerViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IMaskView> : produce_base<D, winrt::RNSVG::IMaskView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IMaskViewManager> : produce_base<D, winrt::RNSVG::IMaskViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IPathView> : produce_base<D, winrt::RNSVG::IPathView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IPathViewManager> : produce_base<D, winrt::RNSVG::IPathViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IPatternView> : produce_base<D, winrt::RNSVG::IPatternView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IPatternViewManager> : produce_base<D, winrt::RNSVG::IPatternViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IRadialGradientView> : produce_base<D, winrt::RNSVG::IRadialGradientView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IRadialGradientViewManager> : produce_base<D, winrt::RNSVG::IRadialGradientViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IReactPackageProvider> : produce_base<D, winrt::RNSVG::IReactPackageProvider>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IRectView> : produce_base<D, winrt::RNSVG::IRectView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IRectViewManager> : produce_base<D, winrt::RNSVG::IRectViewManager>
    {
    };
#endif
    template <typename D>
    struct produce<D, winrt::RNSVG::IRenderable> : produce_base<D, winrt::RNSVG::IRenderable>
    {
        int32_t __stdcall get_Geometry(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::D2DGeometry>(this->shim().Geometry());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_Geometry(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Geometry(*reinterpret_cast<winrt::RNSVG::D2DGeometry const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_IsResponsible(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IsResponsible());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_IsResponsible(bool value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().IsResponsible(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall CreateResources() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CreateResources();
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall Draw(void* deviceContext, winrt::Windows::Foundation::Size size) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Draw(*reinterpret_cast<winrt::RNSVG::D2DDeviceContext const*>(&deviceContext), *reinterpret_cast<winrt::Windows::Foundation::Size const*>(&size));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall MergeProperties(void* other) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MergeProperties(*reinterpret_cast<winrt::RNSVG::IRenderable const*>(&other));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall SaveDefinition() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SaveDefinition();
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall Unload() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Unload();
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall CreateGeometry(void* deviceContext) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().CreateGeometry(*reinterpret_cast<winrt::RNSVG::D2DDeviceContext const*>(&deviceContext));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall HitTest(winrt::Windows::Foundation::Point point, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::RNSVG::IRenderable>(this->shim().HitTest(*reinterpret_cast<winrt::Windows::Foundation::Point const*>(&point)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::RNSVG::IRenderablePaper> : produce_base<D, winrt::RNSVG::IRenderablePaper>
    {
        int32_t __stdcall get_SvgParent(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::UI::Xaml::FrameworkElement>(this->shim().SvgParent());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_SvgParent(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SvgParent(*reinterpret_cast<winrt::Windows::UI::Xaml::FrameworkElement const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall UpdateProperties(void* reader, bool forceUpdate, bool invalidate) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().UpdateProperties(*reinterpret_cast<winrt::Microsoft::ReactNative::IJSValueReader const*>(&reader), forceUpdate, invalidate);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, winrt::RNSVG::IRenderableView> : produce_base<D, winrt::RNSVG::IRenderableView>
    {
        int32_t __stdcall get_IsUnloaded(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IsUnloaded());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Id(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().Id());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_SvgTransform(winrt::Windows::Foundation::Numerics::float3x2* value) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Numerics::float3x2>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Numerics::float3x2>(this->shim().SvgTransform());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_FillOpacity(float* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<float>(this->shim().FillOpacity());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_FillBrushId(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().FillBrushId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StrokeOpacity(float* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<float>(this->shim().StrokeOpacity());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StrokeBrushId(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().StrokeBrushId());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StrokeWidth(struct struct_RNSVG_SVGLength* value) noexcept final try
        {
            zero_abi<winrt::RNSVG::SVGLength>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::SVGLength>(this->shim().StrokeWidth());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StrokeMiterLimit(float* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<float>(this->shim().StrokeMiterLimit());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StrokeDashOffset(float* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<float>(this->shim().StrokeDashOffset());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StrokeDashArray(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>>(this->shim().StrokeDashArray());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StrokeLineCap(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::LineCap>(this->shim().StrokeLineCap());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_StrokeLineJoin(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::LineJoin>(this->shim().StrokeLineJoin());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_FillRule(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::FillRule>(this->shim().FillRule());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall ClipPathGeometry(void* deviceContext, void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::RNSVG::D2DGeometry>(this->shim().ClipPathGeometry(*reinterpret_cast<winrt::RNSVG::D2DDeviceContext const*>(&deviceContext)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IRenderableView2> : produce_base<D, winrt::RNSVG::IRenderableView2>
    {
        int32_t __stdcall get_SvgRoot(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::SvgView>(this->shim().SvgRoot());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Fill(struct struct_Windows_UI_Color* value) noexcept final try
        {
            zero_abi<winrt::Windows::UI::Color>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::UI::Color>(this->shim().Fill());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Stroke(struct struct_Windows_UI_Color* value) noexcept final try
        {
            zero_abi<winrt::Windows::UI::Color>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::UI::Color>(this->shim().Stroke());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IRenderableViewFactory> : produce_base<D, winrt::RNSVG::IRenderableViewFactory>
    {
        int32_t __stdcall CreateInstance(void* context, void* baseInterface, void** innerInterface, void** value) noexcept final try
        {
            if (innerInterface) *innerInterface = nullptr;
            winrt::Windows::Foundation::IInspectable winrt_impl_innerInterface;
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::RenderableView>(this->shim().CreateInstance(*reinterpret_cast<winrt::Microsoft::ReactNative::IReactContext const*>(&context), *reinterpret_cast<winrt::Windows::Foundation::IInspectable const*>(&baseInterface), winrt_impl_innerInterface));
                if (innerInterface) *innerInterface = detach_abi(winrt_impl_innerInterface);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IRenderableViewManager> : produce_base<D, winrt::RNSVG::IRenderableViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IRenderableViewManagerFactory> : produce_base<D, winrt::RNSVG::IRenderableViewManagerFactory>
    {
        int32_t __stdcall CreateInstance(void* baseInterface, void** innerInterface, void** value) noexcept final try
        {
            if (innerInterface) *innerInterface = nullptr;
            winrt::Windows::Foundation::IInspectable winrt_impl_innerInterface;
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::RenderableViewManager>(this->shim().CreateInstance(*reinterpret_cast<winrt::Windows::Foundation::IInspectable const*>(&baseInterface), winrt_impl_innerInterface));
                if (innerInterface) *innerInterface = detach_abi(winrt_impl_innerInterface);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
    template <typename D>
    struct produce<D, winrt::RNSVG::ISvgView> : produce_base<D, winrt::RNSVG::ISvgView>
    {
        int32_t __stdcall get_Device(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::D2DDevice>(this->shim().Device());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_DeviceContext(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::D2DDeviceContext>(this->shim().DeviceContext());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_CanvasSize(winrt::Windows::Foundation::Size* value) noexcept final try
        {
            zero_abi<winrt::Windows::Foundation::Size>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Size>(this->shim().CanvasSize());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Templates(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IMap<hstring, winrt::RNSVG::IRenderable>>(this->shim().Templates());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Brushes(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IMap<hstring, winrt::RNSVG::IBrushView>>(this->shim().Brushes());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall Invalidate() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Invalidate();
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ISvgView2> : produce_base<D, winrt::RNSVG::ISvgView2>
    {
        int32_t __stdcall get_Group(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::GroupView>(this->shim().Group());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_Group(void* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Group(*reinterpret_cast<winrt::RNSVG::GroupView const*>(&value));
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_CurrentColor(struct struct_Windows_UI_Color* value) noexcept final try
        {
            zero_abi<winrt::Windows::UI::Color>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::UI::Color>(this->shim().CurrentColor());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ISvgViewFactory> : produce_base<D, winrt::RNSVG::ISvgViewFactory>
    {
        int32_t __stdcall CreateInstance(void* context, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::SvgView>(this->shim().CreateInstance(*reinterpret_cast<winrt::Microsoft::ReactNative::IReactContext const*>(&context)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ISvgViewManager> : produce_base<D, winrt::RNSVG::ISvgViewManager>
    {
    };
#endif
    template <typename D>
    struct produce<D, winrt::RNSVG::ISymbolView> : produce_base<D, winrt::RNSVG::ISymbolView>
    {
        int32_t __stdcall get_MinX(float* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<float>(this->shim().MinX());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_MinY(float* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<float>(this->shim().MinY());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_VbWidth(float* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<float>(this->shim().VbWidth());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_VbHeight(float* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<float>(this->shim().VbHeight());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Align(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().Align());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_MeetOrSlice(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::MeetOrSlice>(this->shim().MeetOrSlice());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ISymbolView2> : produce_base<D, winrt::RNSVG::ISymbolView2>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ISymbolViewManager> : produce_base<D, winrt::RNSVG::ISymbolViewManager>
    {
    };
#endif
    template <typename D>
    struct produce<D, winrt::RNSVG::ITSpanView> : produce_base<D, winrt::RNSVG::ITSpanView>
    {
        int32_t __stdcall get_Rotate(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>>(this->shim().Rotate());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ITSpanView2> : produce_base<D, winrt::RNSVG::ITSpanView2>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ITSpanViewManager> : produce_base<D, winrt::RNSVG::ITSpanViewManager>
    {
    };
#endif
    template <typename D>
    struct produce<D, winrt::RNSVG::ITextView> : produce_base<D, winrt::RNSVG::ITextView>
    {
        int32_t __stdcall get_X(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>>(this->shim().X());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_Y(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>>(this->shim().Y());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_DX(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>>(this->shim().DX());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall get_DY(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Foundation::Collections::IVector<winrt::RNSVG::SVGLength>>(this->shim().DY());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ITextView2> : produce_base<D, winrt::RNSVG::ITextView2>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ITextViewFactory> : produce_base<D, winrt::RNSVG::ITextViewFactory>
    {
        int32_t __stdcall CreateInstance(void* baseInterface, void** innerInterface, void** value) noexcept final try
        {
            if (innerInterface) *innerInterface = nullptr;
            winrt::Windows::Foundation::IInspectable winrt_impl_innerInterface;
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::TextView>(this->shim().CreateInstance(*reinterpret_cast<winrt::Windows::Foundation::IInspectable const*>(&baseInterface), winrt_impl_innerInterface));
                if (innerInterface) *innerInterface = detach_abi(winrt_impl_innerInterface);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ITextViewManager> : produce_base<D, winrt::RNSVG::ITextViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::ITextViewManagerFactory> : produce_base<D, winrt::RNSVG::ITextViewManagerFactory>
    {
        int32_t __stdcall CreateInstance(void* baseInterface, void** innerInterface, void** value) noexcept final try
        {
            if (innerInterface) *innerInterface = nullptr;
            winrt::Windows::Foundation::IInspectable winrt_impl_innerInterface;
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::TextViewManager>(this->shim().CreateInstance(*reinterpret_cast<winrt::Windows::Foundation::IInspectable const*>(&baseInterface), winrt_impl_innerInterface));
                if (innerInterface) *innerInterface = detach_abi(winrt_impl_innerInterface);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IUnsupportedSvgViewManager> : produce_base<D, winrt::RNSVG::IUnsupportedSvgViewManager>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IUnsupportedSvgViewManagerFactory> : produce_base<D, winrt::RNSVG::IUnsupportedSvgViewManagerFactory>
    {
        int32_t __stdcall CreateInstance(void* name, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::RNSVG::UnsupportedSvgViewManager>(this->shim().CreateInstance(*reinterpret_cast<hstring const*>(&name)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IUseView> : produce_base<D, winrt::RNSVG::IUseView>
    {
    };
#endif
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::RNSVG::IUseViewManager> : produce_base<D, winrt::RNSVG::IUseViewManager>
    {
    };
#endif
}
WINRT_EXPORT namespace winrt::RNSVG
{
    inline BrushView::BrushView()
    {
        winrt::Windows::Foundation::IInspectable baseInterface, innerInterface;
        *this = impl::call_factory<BrushView, IBrushViewFactory>([&](IBrushViewFactory const& f) { return f.CreateInstance(baseInterface, innerInterface); });
    }
    inline CircleView::CircleView() :
        CircleView(impl::call_factory_cast<CircleView(*)(winrt::Windows::Foundation::IActivationFactory const&), CircleView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<CircleView>(); }))
    {
    }
    inline CircleViewManager::CircleViewManager() :
        CircleViewManager(impl::call_factory_cast<CircleViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), CircleViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<CircleViewManager>(); }))
    {
    }
    inline ClipPathView::ClipPathView() :
        ClipPathView(impl::call_factory_cast<ClipPathView(*)(winrt::Windows::Foundation::IActivationFactory const&), ClipPathView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<ClipPathView>(); }))
    {
    }
    inline ClipPathViewManager::ClipPathViewManager() :
        ClipPathViewManager(impl::call_factory_cast<ClipPathViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), ClipPathViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<ClipPathViewManager>(); }))
    {
    }
    inline D2DBrush::D2DBrush() :
        D2DBrush(impl::call_factory_cast<D2DBrush(*)(winrt::Windows::Foundation::IActivationFactory const&), D2DBrush>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<D2DBrush>(); }))
    {
    }
    inline D2DDevice::D2DDevice() :
        D2DDevice(impl::call_factory_cast<D2DDevice(*)(winrt::Windows::Foundation::IActivationFactory const&), D2DDevice>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<D2DDevice>(); }))
    {
    }
    inline D2DDeviceContext::D2DDeviceContext() :
        D2DDeviceContext(impl::call_factory_cast<D2DDeviceContext(*)(winrt::Windows::Foundation::IActivationFactory const&), D2DDeviceContext>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<D2DDeviceContext>(); }))
    {
    }
    inline D2DGeometry::D2DGeometry() :
        D2DGeometry(impl::call_factory_cast<D2DGeometry(*)(winrt::Windows::Foundation::IActivationFactory const&), D2DGeometry>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<D2DGeometry>(); }))
    {
    }
    inline DefsView::DefsView() :
        DefsView(impl::call_factory_cast<DefsView(*)(winrt::Windows::Foundation::IActivationFactory const&), DefsView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<DefsView>(); }))
    {
    }
    inline DefsViewManager::DefsViewManager() :
        DefsViewManager(impl::call_factory_cast<DefsViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), DefsViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<DefsViewManager>(); }))
    {
    }
    inline EllipseView::EllipseView() :
        EllipseView(impl::call_factory_cast<EllipseView(*)(winrt::Windows::Foundation::IActivationFactory const&), EllipseView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<EllipseView>(); }))
    {
    }
    inline EllipseViewManager::EllipseViewManager() :
        EllipseViewManager(impl::call_factory_cast<EllipseViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), EllipseViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<EllipseViewManager>(); }))
    {
    }
    inline GroupView::GroupView(winrt::Microsoft::ReactNative::IReactContext const& context)
    {
        winrt::Windows::Foundation::IInspectable baseInterface, innerInterface;
        *this = impl::call_factory<GroupView, IGroupViewFactory>([&](IGroupViewFactory const& f) { return f.CreateInstance(context, baseInterface, innerInterface); });
    }
    inline GroupViewManager::GroupViewManager()
    {
        winrt::Windows::Foundation::IInspectable baseInterface, innerInterface;
        *this = impl::call_factory<GroupViewManager, IGroupViewManagerFactory>([&](IGroupViewManagerFactory const& f) { return f.CreateInstance(baseInterface, innerInterface); });
    }
    inline ImageView::ImageView() :
        ImageView(impl::call_factory_cast<ImageView(*)(winrt::Windows::Foundation::IActivationFactory const&), ImageView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<ImageView>(); }))
    {
    }
    inline ImageViewManager::ImageViewManager() :
        ImageViewManager(impl::call_factory_cast<ImageViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), ImageViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<ImageViewManager>(); }))
    {
    }
    inline LineView::LineView() :
        LineView(impl::call_factory_cast<LineView(*)(winrt::Windows::Foundation::IActivationFactory const&), LineView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<LineView>(); }))
    {
    }
    inline LineViewManager::LineViewManager() :
        LineViewManager(impl::call_factory_cast<LineViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), LineViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<LineViewManager>(); }))
    {
    }
    inline LinearGradientView::LinearGradientView() :
        LinearGradientView(impl::call_factory_cast<LinearGradientView(*)(winrt::Windows::Foundation::IActivationFactory const&), LinearGradientView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<LinearGradientView>(); }))
    {
    }
    inline LinearGradientViewManager::LinearGradientViewManager() :
        LinearGradientViewManager(impl::call_factory_cast<LinearGradientViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), LinearGradientViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<LinearGradientViewManager>(); }))
    {
    }
    inline MarkerView::MarkerView() :
        MarkerView(impl::call_factory_cast<MarkerView(*)(winrt::Windows::Foundation::IActivationFactory const&), MarkerView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MarkerView>(); }))
    {
    }
    inline MarkerViewManager::MarkerViewManager() :
        MarkerViewManager(impl::call_factory_cast<MarkerViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), MarkerViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MarkerViewManager>(); }))
    {
    }
    inline MaskView::MaskView() :
        MaskView(impl::call_factory_cast<MaskView(*)(winrt::Windows::Foundation::IActivationFactory const&), MaskView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MaskView>(); }))
    {
    }
    inline MaskViewManager::MaskViewManager() :
        MaskViewManager(impl::call_factory_cast<MaskViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), MaskViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MaskViewManager>(); }))
    {
    }
    inline PathView::PathView() :
        PathView(impl::call_factory_cast<PathView(*)(winrt::Windows::Foundation::IActivationFactory const&), PathView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<PathView>(); }))
    {
    }
    inline PathViewManager::PathViewManager() :
        PathViewManager(impl::call_factory_cast<PathViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), PathViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<PathViewManager>(); }))
    {
    }
    inline PatternView::PatternView() :
        PatternView(impl::call_factory_cast<PatternView(*)(winrt::Windows::Foundation::IActivationFactory const&), PatternView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<PatternView>(); }))
    {
    }
    inline PatternViewManager::PatternViewManager() :
        PatternViewManager(impl::call_factory_cast<PatternViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), PatternViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<PatternViewManager>(); }))
    {
    }
    inline RadialGradientView::RadialGradientView() :
        RadialGradientView(impl::call_factory_cast<RadialGradientView(*)(winrt::Windows::Foundation::IActivationFactory const&), RadialGradientView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<RadialGradientView>(); }))
    {
    }
    inline RadialGradientViewManager::RadialGradientViewManager() :
        RadialGradientViewManager(impl::call_factory_cast<RadialGradientViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), RadialGradientViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<RadialGradientViewManager>(); }))
    {
    }
    inline ReactPackageProvider::ReactPackageProvider() :
        ReactPackageProvider(impl::call_factory_cast<ReactPackageProvider(*)(winrt::Windows::Foundation::IActivationFactory const&), ReactPackageProvider>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<ReactPackageProvider>(); }))
    {
    }
    inline RectView::RectView() :
        RectView(impl::call_factory_cast<RectView(*)(winrt::Windows::Foundation::IActivationFactory const&), RectView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<RectView>(); }))
    {
    }
    inline RectViewManager::RectViewManager() :
        RectViewManager(impl::call_factory_cast<RectViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), RectViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<RectViewManager>(); }))
    {
    }
    inline RenderableView::RenderableView(winrt::Microsoft::ReactNative::IReactContext const& context)
    {
        winrt::Windows::Foundation::IInspectable baseInterface, innerInterface;
        *this = impl::call_factory<RenderableView, IRenderableViewFactory>([&](IRenderableViewFactory const& f) { return f.CreateInstance(context, baseInterface, innerInterface); });
    }
    inline RenderableViewManager::RenderableViewManager()
    {
        winrt::Windows::Foundation::IInspectable baseInterface, innerInterface;
        *this = impl::call_factory<RenderableViewManager, IRenderableViewManagerFactory>([&](IRenderableViewManagerFactory const& f) { return f.CreateInstance(baseInterface, innerInterface); });
    }
    inline SvgView::SvgView(winrt::Microsoft::ReactNative::IReactContext const& context) :
        SvgView(impl::call_factory<SvgView, ISvgViewFactory>([&](ISvgViewFactory const& f) { return f.CreateInstance(context); }))
    {
    }
    inline SvgViewManager::SvgViewManager() :
        SvgViewManager(impl::call_factory_cast<SvgViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), SvgViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<SvgViewManager>(); }))
    {
    }
    inline SymbolView::SymbolView() :
        SymbolView(impl::call_factory_cast<SymbolView(*)(winrt::Windows::Foundation::IActivationFactory const&), SymbolView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<SymbolView>(); }))
    {
    }
    inline SymbolViewManager::SymbolViewManager() :
        SymbolViewManager(impl::call_factory_cast<SymbolViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), SymbolViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<SymbolViewManager>(); }))
    {
    }
    inline TSpanView::TSpanView() :
        TSpanView(impl::call_factory_cast<TSpanView(*)(winrt::Windows::Foundation::IActivationFactory const&), TSpanView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<TSpanView>(); }))
    {
    }
    inline TSpanViewManager::TSpanViewManager() :
        TSpanViewManager(impl::call_factory_cast<TSpanViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), TSpanViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<TSpanViewManager>(); }))
    {
    }
    inline TextView::TextView()
    {
        winrt::Windows::Foundation::IInspectable baseInterface, innerInterface;
        *this = impl::call_factory<TextView, ITextViewFactory>([&](ITextViewFactory const& f) { return f.CreateInstance(baseInterface, innerInterface); });
    }
    inline TextViewManager::TextViewManager()
    {
        winrt::Windows::Foundation::IInspectable baseInterface, innerInterface;
        *this = impl::call_factory<TextViewManager, ITextViewManagerFactory>([&](ITextViewManagerFactory const& f) { return f.CreateInstance(baseInterface, innerInterface); });
    }
    inline UnsupportedSvgViewManager::UnsupportedSvgViewManager(param::hstring const& name) :
        UnsupportedSvgViewManager(impl::call_factory<UnsupportedSvgViewManager, IUnsupportedSvgViewManagerFactory>([&](IUnsupportedSvgViewManagerFactory const& f) { return f.CreateInstance(name); }))
    {
    }
    inline UseView::UseView() :
        UseView(impl::call_factory_cast<UseView(*)(winrt::Windows::Foundation::IActivationFactory const&), UseView>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<UseView>(); }))
    {
    }
    inline UseViewManager::UseViewManager() :
        UseViewManager(impl::call_factory_cast<UseViewManager(*)(winrt::Windows::Foundation::IActivationFactory const&), UseViewManager>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<UseViewManager>(); }))
    {
    }
    template <typename D, typename... Interfaces>
    struct BrushViewT :
        implements<D, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, composing, Interfaces...>,
        impl::require<D, winrt::RNSVG::IBrushView2, winrt::RNSVG::IBrushView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>,
        impl::base<D, BrushView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        winrt::Windows::UI::Xaml::IFrameworkElementOverridesT<D>, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2T<D>, winrt::Windows::UI::Xaml::IUIElementOverridesT<D>, winrt::Windows::UI::Xaml::IUIElementOverrides7T<D>, winrt::Windows::UI::Xaml::IUIElementOverrides8T<D>, winrt::Windows::UI::Xaml::IUIElementOverrides9T<D>
    {
        using composable = BrushView;
    protected:
        BrushViewT()
        {
            impl::call_factory<BrushView, IBrushViewFactory>([&](IBrushViewFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
    template <typename D, typename... Interfaces>
    struct GroupViewT :
        implements<D, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, composing, Interfaces...>,
        impl::require<D, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>,
        impl::base<D, GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        winrt::Windows::UI::Xaml::IFrameworkElementOverridesT<D>, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2T<D>, winrt::Windows::UI::Xaml::IUIElementOverridesT<D>, winrt::Windows::UI::Xaml::IUIElementOverrides7T<D>, winrt::Windows::UI::Xaml::IUIElementOverrides8T<D>, winrt::Windows::UI::Xaml::IUIElementOverrides9T<D>
    {
        using composable = GroupView;
    protected:
        GroupViewT(winrt::Microsoft::ReactNative::IReactContext const& context)
        {
            impl::call_factory<GroupView, IGroupViewFactory>([&](IGroupViewFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(context, *this, this->m_inner); });
        }
    };
    template <typename D, typename... Interfaces>
    struct GroupViewManagerT :
        implements<D, winrt::Windows::Foundation::IInspectable, composing, Interfaces...>,
        impl::require<D, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>,
        impl::base<D, GroupViewManager, winrt::RNSVG::RenderableViewManager>
    {
        using composable = GroupViewManager;
    protected:
        GroupViewManagerT()
        {
            impl::call_factory<GroupViewManager, IGroupViewManagerFactory>([&](IGroupViewManagerFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
    template <typename D, typename... Interfaces>
    struct RenderableViewT :
        implements<D, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, composing, Interfaces...>,
        impl::require<D, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>,
        impl::base<D, RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        winrt::Windows::UI::Xaml::IFrameworkElementOverridesT<D>, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2T<D>, winrt::Windows::UI::Xaml::IUIElementOverridesT<D>, winrt::Windows::UI::Xaml::IUIElementOverrides7T<D>, winrt::Windows::UI::Xaml::IUIElementOverrides8T<D>, winrt::Windows::UI::Xaml::IUIElementOverrides9T<D>
    {
        using composable = RenderableView;
    protected:
        RenderableViewT(winrt::Microsoft::ReactNative::IReactContext const& context)
        {
            impl::call_factory<RenderableView, IRenderableViewFactory>([&](IRenderableViewFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(context, *this, this->m_inner); });
        }
    };
    template <typename D, typename... Interfaces>
    struct RenderableViewManagerT :
        implements<D, winrt::Windows::Foundation::IInspectable, composing, Interfaces...>,
        impl::require<D, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>,
        impl::base<D, RenderableViewManager>
    {
        using composable = RenderableViewManager;
    protected:
        RenderableViewManagerT()
        {
            impl::call_factory<RenderableViewManager, IRenderableViewManagerFactory>([&](IRenderableViewManagerFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
    template <typename D, typename... Interfaces>
    struct TextViewT :
        implements<D, winrt::Windows::UI::Xaml::IFrameworkElementOverrides, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2, winrt::Windows::UI::Xaml::IUIElementOverrides, winrt::Windows::UI::Xaml::IUIElementOverrides7, winrt::Windows::UI::Xaml::IUIElementOverrides8, winrt::Windows::UI::Xaml::IUIElementOverrides9, composing, Interfaces...>,
        impl::require<D, winrt::RNSVG::ITextView2, winrt::RNSVG::ITextView, winrt::RNSVG::IGroupView2, winrt::RNSVG::IGroupView, winrt::RNSVG::IRenderableView2, winrt::RNSVG::IRenderable, winrt::RNSVG::IRenderablePaper, winrt::RNSVG::IRenderableView, winrt::Windows::UI::Xaml::IFrameworkElement, winrt::Windows::UI::Xaml::IFrameworkElement2, winrt::Windows::UI::Xaml::IFrameworkElement3, winrt::Windows::UI::Xaml::IFrameworkElement4, winrt::Windows::UI::Xaml::IFrameworkElement6, winrt::Windows::UI::Xaml::IFrameworkElement7, winrt::Windows::UI::Xaml::IFrameworkElementProtected7, winrt::Windows::UI::Xaml::IUIElement, winrt::Windows::UI::Xaml::IUIElement2, winrt::Windows::UI::Xaml::IUIElement3, winrt::Windows::UI::Xaml::IUIElement4, winrt::Windows::UI::Xaml::IUIElement5, winrt::Windows::UI::Xaml::IUIElement7, winrt::Windows::UI::Xaml::IUIElement8, winrt::Windows::UI::Xaml::IUIElement9, winrt::Windows::UI::Xaml::IUIElement10, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Composition::IVisualElement, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>,
        impl::base<D, TextView, winrt::RNSVG::GroupView, winrt::RNSVG::RenderableView, winrt::Windows::UI::Xaml::FrameworkElement, winrt::Windows::UI::Xaml::UIElement, winrt::Windows::UI::Xaml::DependencyObject>,
        winrt::Windows::UI::Xaml::IFrameworkElementOverridesT<D>, winrt::Windows::UI::Xaml::IFrameworkElementOverrides2T<D>, winrt::Windows::UI::Xaml::IUIElementOverridesT<D>, winrt::Windows::UI::Xaml::IUIElementOverrides7T<D>, winrt::Windows::UI::Xaml::IUIElementOverrides8T<D>, winrt::Windows::UI::Xaml::IUIElementOverrides9T<D>
    {
        using composable = TextView;
    protected:
        TextViewT()
        {
            impl::call_factory<TextView, ITextViewFactory>([&](ITextViewFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
    template <typename D, typename... Interfaces>
    struct TextViewManagerT :
        implements<D, winrt::Windows::Foundation::IInspectable, composing, Interfaces...>,
        impl::require<D, winrt::RNSVG::ITextViewManager, winrt::RNSVG::IGroupViewManager, winrt::Microsoft::ReactNative::IViewManagerWithChildren, winrt::RNSVG::IRenderableViewManager, winrt::Microsoft::ReactNative::IViewManager, winrt::Microsoft::ReactNative::IViewManagerWithReactContext, winrt::Microsoft::ReactNative::IViewManagerWithNativeProperties>,
        impl::base<D, TextViewManager, winrt::RNSVG::GroupViewManager, winrt::RNSVG::RenderableViewManager>
    {
        using composable = TextViewManager;
    protected:
        TextViewManagerT()
        {
            impl::call_factory<TextViewManager, ITextViewManagerFactory>([&](ITextViewManagerFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::RNSVG::IBrushView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IBrushView2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IBrushViewFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ICircleView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ICircleViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IClipPathView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IClipPathViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ID2DBrush> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ID2DDevice> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ID2DDeviceContext> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ID2DGeometry> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IDefsView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IDefsViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IEllipseView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IEllipseViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IGroupView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IGroupView2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IGroupViewFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IGroupViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IGroupViewManagerFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IImageView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IImageViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ILineView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ILineViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ILinearGradientView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ILinearGradientViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IMarkerView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IMarkerViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IMaskView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IMaskViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IPathView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IPathViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IPatternView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IPatternViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRadialGradientView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRadialGradientViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IReactPackageProvider> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRectView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRectViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRenderable> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRenderablePaper> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRenderableView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRenderableView2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRenderableViewFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRenderableViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IRenderableViewManagerFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ISvgView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ISvgView2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ISvgViewFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ISvgViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ISymbolView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ISymbolView2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ISymbolViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ITSpanView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ITSpanView2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ITSpanViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ITextView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ITextView2> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ITextViewFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ITextViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ITextViewManagerFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IUnsupportedSvgViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IUnsupportedSvgViewManagerFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IUseView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::IUseViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::BrushView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::CircleView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::CircleViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ClipPathView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ClipPathViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::D2DBrush> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::D2DDevice> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::D2DDeviceContext> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::D2DGeometry> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::DefsView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::DefsViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::EllipseView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::EllipseViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::GroupView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::GroupViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ImageView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ImageViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::LineView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::LineViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::LinearGradientView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::LinearGradientViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::MarkerView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::MarkerViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::MaskView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::MaskViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::PathView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::PathViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::PatternView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::PatternViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::RadialGradientView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::RadialGradientViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::ReactPackageProvider> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::RectView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::RectViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::RenderableView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::RenderableViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::SvgView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::SvgViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::SymbolView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::SymbolViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::TSpanView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::TSpanViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::TextView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::TextViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::UnsupportedSvgViewManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::UseView> : winrt::impl::hash_base {};
    template<> struct hash<winrt::RNSVG::UseViewManager> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
